package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Banks generated by hbm2java
 */
@Entity
@Table(name = "BANKS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"BANK_NAME", "STATUS" }))
public class Banks extends DomainDefault  implements java.io.Serializable {

	private String bankId;
	private String bankName;
	private String regUser;
	private Date regDate;
	private String regIp;
	private BigDecimal status;

	public Banks() {
	}

	public Banks(String bankId, String bankName, Date regDate, String regIp) {
		this.bankId = bankId;
		this.bankName = bankName;
		this.regDate = regDate;
		this.regIp = regIp;
	}

	public Banks(String bankId, String bankName, String regUser, Date regDate,
			String regIp, BigDecimal status) {
		this.bankId = bankId;
		this.bankName = bankName;
		this.regUser = regUser;
		this.regDate = regDate;
		this.regIp = regIp;
		this.status = status;
	}

	@Id
	@Column(name = "BANK_ID", unique = true, nullable = false, length = 10)
	public String getBankId() {
		return this.bankId;
	}

	public void setBankId(String bankId) {
		this.bankId = bankId;
	}

	@Column(name = "BANK_NAME", nullable = false, length = 100)
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "REG_USER", length = 20)
	public String getRegUser() {
		return this.regUser;
	}

	public void setRegUser(String regUser) {
		this.regUser = regUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REG_DATE", nullable = false, length = 7)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "REG_IP", nullable = false, length = 15)
	public String getRegIp() {
		return this.regIp;
	}

	public void setRegIp(String regIp) {
		this.regIp = regIp;
	}

	@Column(name = "STATUS", precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

}
