package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BeforeVerificationItem generated by hbm2java
 */
@Entity
@Table(name = "BEFORE_VERIFICATION_ITEM")
public class BeforeVerificationItem implements java.io.Serializable {

	private BeforeVerificationItemId id;
	private PharmacyUnit pharmacyUnit;
	private double computerStock;
	private BigDecimal costPrice;

	public BeforeVerificationItem() {
	}

	public BeforeVerificationItem(BeforeVerificationItemId id,
			PharmacyUnit pharmacyUnit, double computerStock,
			BigDecimal costPrice) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.computerStock = computerStock;
		this.costPrice = costPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "beforeVerificationNo", column = @Column(name = "BEFORE_VERIFICATION_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)) })
	public BeforeVerificationItemId getId() {
		return this.id;
	}

	public void setId(BeforeVerificationItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Column(name = "COMPUTER_STOCK", nullable = false, precision = 126, scale = 0)
	public double getComputerStock() {
		return this.computerStock;
	}

	public void setComputerStock(double computerStock) {
		this.computerStock = computerStock;
	}

	@Column(name = "COST_PRICE", nullable = false, precision = 10)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

}
