package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BeforeVerificationItemId generated by hbm2java
 */
@Embeddable
public class BeforeVerificationItemId implements java.io.Serializable {

	private String beforeVerificationNo;
	private String itemNo;
	private String phUnitNo;
	private String grnNo;

	public BeforeVerificationItemId() {
	}

	public BeforeVerificationItemId(String beforeVerificationNo, String itemNo,
			String phUnitNo, String grnNo) {
		this.beforeVerificationNo = beforeVerificationNo;
		this.itemNo = itemNo;
		this.phUnitNo = phUnitNo;
		this.grnNo = grnNo;
	}

	@Column(name = "BEFORE_VERIFICATION_NO", nullable = false, length = 20)
	public String getBeforeVerificationNo() {
		return this.beforeVerificationNo;
	}

	public void setBeforeVerificationNo(String beforeVerificationNo) {
		this.beforeVerificationNo = beforeVerificationNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "GRN_NO", nullable = false, length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BeforeVerificationItemId))
			return false;
		BeforeVerificationItemId castOther = (BeforeVerificationItemId) other;

		return ((this.getBeforeVerificationNo() == castOther
				.getBeforeVerificationNo()) || (this.getBeforeVerificationNo() != null
				&& castOther.getBeforeVerificationNo() != null && this
				.getBeforeVerificationNo().equals(
						castOther.getBeforeVerificationNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null && castOther.getItemNo() != null && this
						.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
						.getPhUnitNo() != null
						&& castOther.getPhUnitNo() != null && this
						.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getGrnNo() == castOther.getGrnNo()) || (this
						.getGrnNo() != null && castOther.getGrnNo() != null && this
						.getGrnNo().equals(castOther.getGrnNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getBeforeVerificationNo() == null ? 0 : this
						.getBeforeVerificationNo().hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37 * result
				+ (getGrnNo() == null ? 0 : this.getGrnNo().hashCode());
		return result;
	}

}
