package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BeforeVerification generated by hbm2java
 */
@Entity
@Table(name = "BEFORE_VERIFICATION")
public class BeforeVerification implements java.io.Serializable {

	private BeforeVerificationId id;
	private PharmacyUnit pharmacyUnit;
	private Date beforeVerificationDate;
	private String userId;
	private String userIp;
	private BigDecimal status;

	public BeforeVerification() {
	}

	public BeforeVerification(BeforeVerificationId id,
			PharmacyUnit pharmacyUnit, Date beforeVerificationDate,
			String userId, String userIp, BigDecimal status) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.beforeVerificationDate = beforeVerificationDate;
		this.userId = userId;
		this.userIp = userIp;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "beforeVerificationNo", column = @Column(name = "BEFORE_VERIFICATION_NO", nullable = false, length = 20)) })
	public BeforeVerificationId getId() {
		return this.id;
	}

	public void setId(BeforeVerificationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BEFORE_VERIFICATION_DATE", nullable = false, length = 7)
	public Date getBeforeVerificationDate() {
		return this.beforeVerificationDate;
	}

	public void setBeforeVerificationDate(Date beforeVerificationDate) {
		this.beforeVerificationDate = beforeVerificationDate;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

}
