package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CardRates generated by hbm2java
 */
@Entity
@Table(name = "CARD_RATES")
public class CardRates implements java.io.Serializable {

	private CardRatesId id;
	private LoyalityCards loyalityCards;
	private double rate;
	private Date regDate;
	private String userId;
	private String userIp;

	public CardRates() {
	}

	public CardRates(CardRatesId id, LoyalityCards loyalityCards, double rate,
			Date regDate, String userId, String userIp) {
		this.id = id;
		this.loyalityCards = loyalityCards;
		this.rate = rate;
		this.regDate = regDate;
		this.userId = userId;
		this.userIp = userIp;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cardNo", column = @Column(name = "CARD_NO", nullable = false, length = 10)),
			@AttributeOverride(name = "minValue", column = @Column(name = "MIN_VALUE", nullable = false, precision = 126, scale = 0)),
			@AttributeOverride(name = "maxValue", column = @Column(name = "MAX_VALUE", nullable = false, precision = 126, scale = 0)) })
	public CardRatesId getId() {
		return this.id;
	}

	public void setId(CardRatesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD_NO", nullable = false, insertable = false, updatable = false)
	public LoyalityCards getLoyalityCards() {
		return this.loyalityCards;
	}

	public void setLoyalityCards(LoyalityCards loyalityCards) {
		this.loyalityCards = loyalityCards;
	}

	@Column(name = "RATE", nullable = false, precision = 126, scale = 0)
	public double getRate() {
		return this.rate;
	}

	public void setRate(double rate) {
		this.rate = rate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REG_DATE", nullable = false, length = 7)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

}
