package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CardRatesId generated by hbm2java
 */
@Embeddable
public class CardRatesId implements java.io.Serializable {

	private String cardNo;
	private double minValue;
	private double maxValue;

	public CardRatesId() {
	}

	public CardRatesId(String cardNo, double minValue, double maxValue) {
		this.cardNo = cardNo;
		this.minValue = minValue;
		this.maxValue = maxValue;
	}

	@Column(name = "CARD_NO", nullable = false, length = 10)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "MIN_VALUE", nullable = false, precision = 126, scale = 0)
	public double getMinValue() {
		return this.minValue;
	}

	public void setMinValue(double minValue) {
		this.minValue = minValue;
	}

	@Column(name = "MAX_VALUE", nullable = false, precision = 126, scale = 0)
	public double getMaxValue() {
		return this.maxValue;
	}

	public void setMaxValue(double maxValue) {
		this.maxValue = maxValue;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CardRatesId))
			return false;
		CardRatesId castOther = (CardRatesId) other;

		return ((this.getCardNo() == castOther.getCardNo()) || (this
				.getCardNo() != null && castOther.getCardNo() != null && this
				.getCardNo().equals(castOther.getCardNo())))
				&& (this.getMinValue() == castOther.getMinValue())
				&& (this.getMaxValue() == castOther.getMaxValue());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCardNo() == null ? 0 : this.getCardNo().hashCode());
		result = 37 * result + (int) this.getMinValue();
		result = 37 * result + (int) this.getMaxValue();
		return result;
	}

}
