package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CreditCompanies generated by hbm2java
 */
@Entity
@Table(name = "CREDIT_COMPANIES", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class CreditCompanies implements java.io.Serializable {

	private CreditCompaniesId id;
	private String name;
	private String address1;
	private String tele;
	private String fax;
	private BigDecimal creditLimit;
	private Byte status;
	private Date regDate;
	private String regUser;
	private String address2;
	private String address3;
	private String collector;

	public CreditCompanies() {
	}

	public CreditCompanies(CreditCompaniesId id) {
		this.id = id;
	}

	public CreditCompanies(CreditCompaniesId id, String name, String address1,
			String tele, String fax, BigDecimal creditLimit, Byte status,
			Date regDate, String regUser, String address2, String address3,
			String collector) {
		this.id = id;
		this.name = name;
		this.address1 = address1;
		this.tele = tele;
		this.fax = fax;
		this.creditLimit = creditLimit;
		this.status = status;
		this.regDate = regDate;
		this.regUser = regUser;
		this.address2 = address2;
		this.address3 = address3;
		this.collector = collector;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 10)),
			@AttributeOverride(name = "opdInword", column = @Column(name = "OPD_INWORD", nullable = false, precision = 2, scale = 0)) })
	public CreditCompaniesId getId() {
		return this.id;
	}

	public void setId(CreditCompaniesId id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ADDRESS1", length = 200)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "TELE", length = 30)
	public String getTele() {
		return this.tele;
	}

	public void setTele(String tele) {
		this.tele = tele;
	}

	@Column(name = "FAX", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "CREDIT_LIMIT", precision = 20)
	public BigDecimal getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(BigDecimal creditLimit) {
		this.creditLimit = creditLimit;
	}

	@Column(name = "STATUS", precision = 2, scale = 0)
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REG_DATE", length = 7)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "REG_USER", length = 30)
	public String getRegUser() {
		return this.regUser;
	}

	public void setRegUser(String regUser) {
		this.regUser = regUser;
	}

	@Column(name = "ADDRESS2", length = 200)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "ADDRESS3", length = 200)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "COLLECTOR", length = 200)
	public String getCollector() {
		return this.collector;
	}

	public void setCollector(String collector) {
		this.collector = collector;
	}

}
