package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CreditCompaniesId generated by hbm2java
 */
@Embeddable
public class CreditCompaniesId implements java.io.Serializable {

	private String phUnitNo;
	private String id;
	private byte opdInword;

	public CreditCompaniesId() {
	}

	public CreditCompaniesId(String phUnitNo, String id, byte opdInword) {
		this.phUnitNo = phUnitNo;
		this.id = id;
		this.opdInword = opdInword;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "ID", nullable = false, length = 10)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "OPD_INWORD", nullable = false, precision = 2, scale = 0)
	public byte getOpdInword() {
		return this.opdInword;
	}

	public void setOpdInword(byte opdInword) {
		this.opdInword = opdInword;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CreditCompaniesId))
			return false;
		CreditCompaniesId castOther = (CreditCompaniesId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& (this.getOpdInword() == castOther.getOpdInword());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + this.getOpdInword();
		return result;
	}

}
