package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustPointSpends generated by hbm2java
 */
@Entity
@Table(name = "CUST_POINT_SPENDS")
public class CustPointSpends implements java.io.Serializable {

	private CustPointSpendsId id;
	private LoyalityCards loyalityCards;
	private Date spendDate;
	private String invoiceNo;
	private BigDecimal status;
	private double points;

	public CustPointSpends() {
	}

	public CustPointSpends(CustPointSpendsId id, LoyalityCards loyalityCards,
			Date spendDate, String invoiceNo, BigDecimal status, double points) {
		this.id = id;
		this.loyalityCards = loyalityCards;
		this.spendDate = spendDate;
		this.invoiceNo = invoiceNo;
		this.status = status;
		this.points = points;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "custNo", column = @Column(name = "CUST_NO", nullable = false, length = 10)),
			@AttributeOverride(name = "cardNo", column = @Column(name = "CARD_NO", nullable = false, length = 10)) })
	public CustPointSpendsId getId() {
		return this.id;
	}

	public void setId(CustPointSpendsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CARD_NO", nullable = false, insertable = false, updatable = false)
	public LoyalityCards getLoyalityCards() {
		return this.loyalityCards;
	}

	public void setLoyalityCards(LoyalityCards loyalityCards) {
		this.loyalityCards = loyalityCards;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SPEND_DATE", nullable = false, length = 7)
	public Date getSpendDate() {
		return this.spendDate;
	}

	public void setSpendDate(Date spendDate) {
		this.spendDate = spendDate;
	}

	@Column(name = "INVOICE_NO", nullable = false, length = 10)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Column(name = "STATUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Column(name = "POINTS", nullable = false, precision = 126, scale = 0)
	public double getPoints() {
		return this.points;
	}

	public void setPoints(double points) {
		this.points = points;
	}

}
