package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CustPointSpendsId generated by hbm2java
 */
@Embeddable
public class CustPointSpendsId implements java.io.Serializable {

	private String custNo;
	private String cardNo;

	public CustPointSpendsId() {
	}

	public CustPointSpendsId(String custNo, String cardNo) {
		this.custNo = custNo;
		this.cardNo = cardNo;
	}

	@Column(name = "CUST_NO", nullable = false, length = 10)
	public String getCustNo() {
		return this.custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	@Column(name = "CARD_NO", nullable = false, length = 10)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CustPointSpendsId))
			return false;
		CustPointSpendsId castOther = (CustPointSpendsId) other;

		return ((this.getCustNo() == castOther.getCustNo()) || (this
				.getCustNo() != null && castOther.getCustNo() != null && this
				.getCustNo().equals(castOther.getCustNo())))
				&& ((this.getCardNo() == castOther.getCardNo()) || (this
						.getCardNo() != null && castOther.getCardNo() != null && this
						.getCardNo().equals(castOther.getCardNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCustNo() == null ? 0 : this.getCustNo().hashCode());
		result = 37 * result
				+ (getCardNo() == null ? 0 : this.getCardNo().hashCode());
		return result;
	}

}
