package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DirrectIssueToUnitItem generated by hbm2java
 */
@Entity
@Table(name = "DIRRECT_ISSUE_TO_UNIT_ITEM")
public class DirrectIssueToUnitItem implements java.io.Serializable {

	private DirrectIssueToUnitItemId id;
	private DirrectIssueToUnit dirrectIssueToUnit;
	private double quantity;
	private BigDecimal costPrice;

	public DirrectIssueToUnitItem() {
	}

	public DirrectIssueToUnitItem(DirrectIssueToUnitItemId id,
			DirrectIssueToUnit dirrectIssueToUnit, double quantity,
			BigDecimal costPrice) {
		this.id = id;
		this.dirrectIssueToUnit = dirrectIssueToUnit;
		this.quantity = quantity;
		this.costPrice = costPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "dirrectIssueNo", column = @Column(name = "DIRRECT_ISSUE_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)) })
	public DirrectIssueToUnitItemId getId() {
		return this.id;
	}

	public void setId(DirrectIssueToUnitItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIRRECT_ISSUE_NO", nullable = false, insertable = false, updatable = false)
	public DirrectIssueToUnit getDirrectIssueToUnit() {
		return this.dirrectIssueToUnit;
	}

	public void setDirrectIssueToUnit(DirrectIssueToUnit dirrectIssueToUnit) {
		this.dirrectIssueToUnit = dirrectIssueToUnit;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "COST_PRICE", nullable = false, precision = 10)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

}
