package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DirrectIssueToUnitItemId generated by hbm2java
 */
@Embeddable
public class DirrectIssueToUnitItemId implements java.io.Serializable {

	private String itemNo;
	private String dirrectIssueNo;
	private String grnNo;

	public DirrectIssueToUnitItemId() {
	}

	public DirrectIssueToUnitItemId(String itemNo, String dirrectIssueNo,
			String grnNo) {
		this.itemNo = itemNo;
		this.dirrectIssueNo = dirrectIssueNo;
		this.grnNo = grnNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "DIRRECT_ISSUE_NO", nullable = false, length = 20)
	public String getDirrectIssueNo() {
		return this.dirrectIssueNo;
	}

	public void setDirrectIssueNo(String dirrectIssueNo) {
		this.dirrectIssueNo = dirrectIssueNo;
	}

	@Column(name = "GRN_NO", nullable = false, length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DirrectIssueToUnitItemId))
			return false;
		DirrectIssueToUnitItemId castOther = (DirrectIssueToUnitItemId) other;

		return ((this.getItemNo() == castOther.getItemNo()) || (this
				.getItemNo() != null && castOther.getItemNo() != null && this
				.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getDirrectIssueNo() == castOther.getDirrectIssueNo()) || (this
						.getDirrectIssueNo() != null
						&& castOther.getDirrectIssueNo() != null && this
						.getDirrectIssueNo().equals(
								castOther.getDirrectIssueNo())))
				&& ((this.getGrnNo() == castOther.getGrnNo()) || (this
						.getGrnNo() != null && castOther.getGrnNo() != null && this
						.getGrnNo().equals(castOther.getGrnNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37
				* result
				+ (getDirrectIssueNo() == null ? 0 : this.getDirrectIssueNo()
						.hashCode());
		result = 37 * result
				+ (getGrnNo() == null ? 0 : this.getGrnNo().hashCode());
		return result;
	}

}
