package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Doctors generated by hbm2java
 */
@Entity
@Table(name = "DOCTORS")
public class Doctors implements java.io.Serializable {

	private String docNo;
	private String title;
	private String firstName;
	private String lastName;
	private String specialization;
	private String homeTele;
	private String officeTele;
	private String mobile;
	private String address;
	private String email;
	private Byte status;
	private Date txndate;
	private String txnUser;
	private Byte doctorType;

	public Doctors() {
	}

	public Doctors(String docNo) {
		this.docNo = docNo;
	}

	public Doctors(String docNo, String title, String firstName,
			String lastName, String specialization, String homeTele,
			String officeTele, String mobile, String address, String email,
			Byte status, Date txndate, String txnUser, Byte doctorType) {
		this.docNo = docNo;
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.specialization = specialization;
		this.homeTele = homeTele;
		this.officeTele = officeTele;
		this.mobile = mobile;
		this.address = address;
		this.email = email;
		this.status = status;
		this.txndate = txndate;
		this.txnUser = txnUser;
		this.doctorType = doctorType;
	}

	@Id
	@Column(name = "DOC_NO", unique = true, nullable = false, length = 10)
	public String getDocNo() {
		return this.docNo;
	}

	public void setDocNo(String docNo) {
		this.docNo = docNo;
	}

	@Column(name = "TITLE", length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "FIRST_NAME", length = 200)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 200)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "SPECIALIZATION", length = 100)
	public String getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(String specialization) {
		this.specialization = specialization;
	}

	@Column(name = "HOME_TELE", length = 30)
	public String getHomeTele() {
		return this.homeTele;
	}

	public void setHomeTele(String homeTele) {
		this.homeTele = homeTele;
	}

	@Column(name = "OFFICE_TELE", length = 30)
	public String getOfficeTele() {
		return this.officeTele;
	}

	public void setOfficeTele(String officeTele) {
		this.officeTele = officeTele;
	}

	@Column(name = "MOBILE", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "ADDRESS", length = 200)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "EMAIL", length = 70)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "STATUS", precision = 2, scale = 0)
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TXNDATE", length = 7)
	public Date getTxndate() {
		return this.txndate;
	}

	public void setTxndate(Date txndate) {
		this.txndate = txndate;
	}

	@Column(name = "TXN_USER", length = 30)
	public String getTxnUser() {
		return this.txnUser;
	}

	public void setTxnUser(String txnUser) {
		this.txnUser = txnUser;
	}

	@Column(name = "DOCTOR_TYPE", precision = 2, scale = 0)
	public Byte getDoctorType() {
		return this.doctorType;
	}

	public void setDoctorType(Byte doctorType) {
		this.doctorType = doctorType;
	}

}
