package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DrugItemPharmacyUnit generated by hbm2java
 */
@Entity
@Table(name = "DRUG_ITEM_PHARMACY_UNIT")
public class DrugItemPharmacyUnit implements java.io.Serializable {

	private DrugItemPharmacyUnitId id;
	private PharmacyUnit pharmacyUnit;
	private Supplier supplier;
	private double rol;
	private double roq;
	private BigDecimal currentStatus;
	private BigDecimal drugType;
	private Double margin;
	private Set<ItemMovement> itemMovements = new HashSet<ItemMovement>(0);
	private Set<DrugItemUnitQuantity> drugItemUnitQuantities = new HashSet<DrugItemUnitQuantity>(
			0);

	public DrugItemPharmacyUnit() {
	}

	public DrugItemPharmacyUnit(DrugItemPharmacyUnitId id,
			PharmacyUnit pharmacyUnit, Supplier supplier, double rol,
			double roq, BigDecimal currentStatus, BigDecimal drugType) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.supplier = supplier;
		this.rol = rol;
		this.roq = roq;
		this.currentStatus = currentStatus;
		this.drugType = drugType;
	}

	public DrugItemPharmacyUnit(DrugItemPharmacyUnitId id,
			PharmacyUnit pharmacyUnit, Supplier supplier, double rol,
			double roq, BigDecimal currentStatus, BigDecimal drugType,
			Double margin, Set<ItemMovement> itemMovements,
			Set<DrugItemUnitQuantity> drugItemUnitQuantities) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.supplier = supplier;
		this.rol = rol;
		this.roq = roq;
		this.currentStatus = currentStatus;
		this.drugType = drugType;
		this.margin = margin;
		this.itemMovements = itemMovements;
		this.drugItemUnitQuantities = drugItemUnitQuantities;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "unitNo", column = @Column(name = "UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)) })
	public DrugItemPharmacyUnitId getId() {
		return this.id;
	}

	public void setId(DrugItemPharmacyUnitId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SUP_NO", referencedColumnName = "SUP_NO", nullable = false),
			@JoinColumn(name = "PH_UNIT_NO", referencedColumnName = "PH_UNIT_NO", nullable = false) })
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "ROL", nullable = false, precision = 126, scale = 0)
	public double getRol() {
		return this.rol;
	}

	public void setRol(double rol) {
		this.rol = rol;
	}

	@Column(name = "ROQ", nullable = false, precision = 126, scale = 0)
	public double getRoq() {
		return this.roq;
	}

	public void setRoq(double roq) {
		this.roq = roq;
	}

	@Column(name = "CURRENT_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getCurrentStatus() {
		return this.currentStatus;
	}

	public void setCurrentStatus(BigDecimal currentStatus) {
		this.currentStatus = currentStatus;
	}

	@Column(name = "DRUG_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getDrugType() {
		return this.drugType;
	}

	public void setDrugType(BigDecimal drugType) {
		this.drugType = drugType;
	}

	@Column(name = "MARGIN", precision = 126, scale = 0)
	public Double getMargin() {
		return this.margin;
	}

	public void setMargin(Double margin) {
		this.margin = margin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drugItemPharmacyUnit")
	public Set<ItemMovement> getItemMovements() {
		return this.itemMovements;
	}

	public void setItemMovements(Set<ItemMovement> itemMovements) {
		this.itemMovements = itemMovements;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "drugItemPharmacyUnit")
	public Set<DrugItemUnitQuantity> getDrugItemUnitQuantities() {
		return this.drugItemUnitQuantities;
	}

	public void setDrugItemUnitQuantities(
			Set<DrugItemUnitQuantity> drugItemUnitQuantities) {
		this.drugItemUnitQuantities = drugItemUnitQuantities;
	}

}
