package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DrugItemUnitQuantity generated by hbm2java
 */
@Entity
@Table(name = "DRUG_ITEM_UNIT_QUANTITY")
public class DrugItemUnitQuantity implements java.io.Serializable {

	private DrugItemUnitQuantityId id;
	private DrugItemPharmacyUnit drugItemPharmacyUnit;
	private Grn grn;
	private double quantity;

	public DrugItemUnitQuantity() {
	}

	public DrugItemUnitQuantity(DrugItemUnitQuantityId id,
			DrugItemPharmacyUnit drugItemPharmacyUnit, Grn grn, double quantity) {
		this.id = id;
		this.drugItemPharmacyUnit = drugItemPharmacyUnit;
		this.grn = grn;
		this.quantity = quantity;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "unitNo", column = @Column(name = "UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)) })
	public DrugItemUnitQuantityId getId() {
		return this.id;
	}

	public void setId(DrugItemUnitQuantityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "UNIT_NO", referencedColumnName = "UNIT_NO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ITEM_NO", referencedColumnName = "ITEM_NO", nullable = false, insertable = false, updatable = false) })
	public DrugItemPharmacyUnit getDrugItemPharmacyUnit() {
		return this.drugItemPharmacyUnit;
	}

	public void setDrugItemPharmacyUnit(
			DrugItemPharmacyUnit drugItemPharmacyUnit) {
		this.drugItemPharmacyUnit = drugItemPharmacyUnit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "UNIT_NO_GRN", referencedColumnName = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "GRN_NO", referencedColumnName = "GRN_NO", nullable = false, insertable = false, updatable = false) })
	public Grn getGrn() {
		return this.grn;
	}

	public void setGrn(Grn grn) {
		this.grn = grn;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

}
