package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * EpharmaInstalments generated by hbm2java
 */
@Entity
@Table(name = "EPHARMA_INSTALMENTS", uniqueConstraints = @UniqueConstraint(columnNames = "KEY"))
public class EpharmaInstalments implements java.io.Serializable {

	private BigDecimal no;
	private Date txnDate;
	private String txnIp;
	private String key;
	private BigDecimal validDays;

	public EpharmaInstalments() {
	}

	public EpharmaInstalments(BigDecimal no, Date txnDate, String txnIp,
			String key, BigDecimal validDays) {
		this.no = no;
		this.txnDate = txnDate;
		this.txnIp = txnIp;
		this.key = key;
		this.validDays = validDays;
	}

	@Id
	@Column(name = "NO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getNo() {
		return this.no;
	}

	public void setNo(BigDecimal no) {
		this.no = no;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TXN_DATE", nullable = false, length = 7)
	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	@Column(name = "TXN_IP", nullable = false, length = 50)
	public String getTxnIp() {
		return this.txnIp;
	}

	public void setTxnIp(String txnIp) {
		this.txnIp = txnIp;
	}

	@Column(name = "KEY", unique = true, nullable = false, length = 50)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "VALID_DAYS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getValidDays() {
		return this.validDays;
	}

	public void setValidDays(BigDecimal validDays) {
		this.validDays = validDays;
	}

}
