package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EpharmaSystemInfoId generated by hbm2java
 */
@Embeddable
public class EpharmaSystemInfoId implements java.io.Serializable {

	private String systemOwner;
	private Date sysDate;
	private String currVersion;
	private BigDecimal enablePrintouts;
	private String sysMacKey;
	private Date regDate;
	private String isRegDate;
	private String isSysDate;
	private Date renewDate;
	private String isRnd;

	public EpharmaSystemInfoId() {
	}

	public EpharmaSystemInfoId(String systemOwner, Date sysDate,
			String currVersion, BigDecimal enablePrintouts) {
		this.systemOwner = systemOwner;
		this.sysDate = sysDate;
		this.currVersion = currVersion;
		this.enablePrintouts = enablePrintouts;
	}

	public EpharmaSystemInfoId(String systemOwner, Date sysDate,
			String currVersion, BigDecimal enablePrintouts, String sysMacKey,
			Date regDate, String isRegDate, String isSysDate, Date renewDate,
			String isRnd) {
		this.systemOwner = systemOwner;
		this.sysDate = sysDate;
		this.currVersion = currVersion;
		this.enablePrintouts = enablePrintouts;
		this.sysMacKey = sysMacKey;
		this.regDate = regDate;
		this.isRegDate = isRegDate;
		this.isSysDate = isSysDate;
		this.renewDate = renewDate;
		this.isRnd = isRnd;
	}

	@Column(name = "SYSTEM_OWNER", nullable = false, length = 100)
	public String getSystemOwner() {
		return this.systemOwner;
	}

	public void setSystemOwner(String systemOwner) {
		this.systemOwner = systemOwner;
	}

	@Column(name = "SYS_DATE", nullable = false, length = 7)
	public Date getSysDate() {
		return this.sysDate;
	}

	public void setSysDate(Date sysDate) {
		this.sysDate = sysDate;
	}

	@Column(name = "CURR_VERSION", nullable = false, length = 50)
	public String getCurrVersion() {
		return this.currVersion;
	}

	public void setCurrVersion(String currVersion) {
		this.currVersion = currVersion;
	}

	@Column(name = "ENABLE_PRINTOUTS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getEnablePrintouts() {
		return this.enablePrintouts;
	}

	public void setEnablePrintouts(BigDecimal enablePrintouts) {
		this.enablePrintouts = enablePrintouts;
	}

	@Column(name = "SYS_MAC_KEY", length = 100)
	public String getSysMacKey() {
		return this.sysMacKey;
	}

	public void setSysMacKey(String sysMacKey) {
		this.sysMacKey = sysMacKey;
	}

	@Column(name = "REG_DATE", length = 7)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "IS_REG_DATE", length = 100)
	public String getIsRegDate() {
		return this.isRegDate;
	}

	public void setIsRegDate(String isRegDate) {
		this.isRegDate = isRegDate;
	}

	@Column(name = "IS_SYS_DATE", length = 100)
	public String getIsSysDate() {
		return this.isSysDate;
	}

	public void setIsSysDate(String isSysDate) {
		this.isSysDate = isSysDate;
	}

	@Column(name = "RENEW_DATE", length = 7)
	public Date getRenewDate() {
		return this.renewDate;
	}

	public void setRenewDate(Date renewDate) {
		this.renewDate = renewDate;
	}

	@Column(name = "IS_RND", length = 100)
	public String getIsRnd() {
		return this.isRnd;
	}

	public void setIsRnd(String isRnd) {
		this.isRnd = isRnd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EpharmaSystemInfoId))
			return false;
		EpharmaSystemInfoId castOther = (EpharmaSystemInfoId) other;

		return ((this.getSystemOwner() == castOther.getSystemOwner()) || (this
				.getSystemOwner() != null && castOther.getSystemOwner() != null && this
				.getSystemOwner().equals(castOther.getSystemOwner())))
				&& ((this.getSysDate() == castOther.getSysDate()) || (this
						.getSysDate() != null && castOther.getSysDate() != null && this
						.getSysDate().equals(castOther.getSysDate())))
				&& ((this.getCurrVersion() == castOther.getCurrVersion()) || (this
						.getCurrVersion() != null
						&& castOther.getCurrVersion() != null && this
						.getCurrVersion().equals(castOther.getCurrVersion())))
				&& ((this.getEnablePrintouts() == castOther
						.getEnablePrintouts()) || (this.getEnablePrintouts() != null
						&& castOther.getEnablePrintouts() != null && this
						.getEnablePrintouts().equals(
								castOther.getEnablePrintouts())))
				&& ((this.getSysMacKey() == castOther.getSysMacKey()) || (this
						.getSysMacKey() != null
						&& castOther.getSysMacKey() != null && this
						.getSysMacKey().equals(castOther.getSysMacKey())))
				&& ((this.getRegDate() == castOther.getRegDate()) || (this
						.getRegDate() != null && castOther.getRegDate() != null && this
						.getRegDate().equals(castOther.getRegDate())))
				&& ((this.getIsRegDate() == castOther.getIsRegDate()) || (this
						.getIsRegDate() != null
						&& castOther.getIsRegDate() != null && this
						.getIsRegDate().equals(castOther.getIsRegDate())))
				&& ((this.getIsSysDate() == castOther.getIsSysDate()) || (this
						.getIsSysDate() != null
						&& castOther.getIsSysDate() != null && this
						.getIsSysDate().equals(castOther.getIsSysDate())))
				&& ((this.getRenewDate() == castOther.getRenewDate()) || (this
						.getRenewDate() != null
						&& castOther.getRenewDate() != null && this
						.getRenewDate().equals(castOther.getRenewDate())))
				&& ((this.getIsRnd() == castOther.getIsRnd()) || (this
						.getIsRnd() != null && castOther.getIsRnd() != null && this
						.getIsRnd().equals(castOther.getIsRnd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSystemOwner() == null ? 0 : this.getSystemOwner()
						.hashCode());
		result = 37 * result
				+ (getSysDate() == null ? 0 : this.getSysDate().hashCode());
		result = 37
				* result
				+ (getCurrVersion() == null ? 0 : this.getCurrVersion()
						.hashCode());
		result = 37
				* result
				+ (getEnablePrintouts() == null ? 0 : this.getEnablePrintouts()
						.hashCode());
		result = 37 * result
				+ (getSysMacKey() == null ? 0 : this.getSysMacKey().hashCode());
		result = 37 * result
				+ (getRegDate() == null ? 0 : this.getRegDate().hashCode());
		result = 37 * result
				+ (getIsRegDate() == null ? 0 : this.getIsRegDate().hashCode());
		result = 37 * result
				+ (getIsSysDate() == null ? 0 : this.getIsSysDate().hashCode());
		result = 37 * result
				+ (getRenewDate() == null ? 0 : this.getRenewDate().hashCode());
		result = 37 * result
				+ (getIsRnd() == null ? 0 : this.getIsRnd().hashCode());
		return result;
	}

}
