package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EpharmaSystemInfo generated by hbm2java
 */
@Entity
@Table(name = "EPHARMA_SYSTEM_INFO")
public class EpharmaSystemInfo implements java.io.Serializable {

	private EpharmaSystemInfoId id;

	public EpharmaSystemInfo() {
	}

	public EpharmaSystemInfo(EpharmaSystemInfoId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "systemOwner", column = @Column(name = "SYSTEM_OWNER", nullable = false, length = 100)),
			@AttributeOverride(name = "sysDate", column = @Column(name = "SYS_DATE", nullable = false, length = 7)),
			@AttributeOverride(name = "currVersion", column = @Column(name = "CURR_VERSION", nullable = false, length = 50)),
			@AttributeOverride(name = "enablePrintouts", column = @Column(name = "ENABLE_PRINTOUTS", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "sysMacKey", column = @Column(name = "SYS_MAC_KEY", length = 100)),
			@AttributeOverride(name = "regDate", column = @Column(name = "REG_DATE", length = 7)),
			@AttributeOverride(name = "isRegDate", column = @Column(name = "IS_REG_DATE", length = 100)),
			@AttributeOverride(name = "isSysDate", column = @Column(name = "IS_SYS_DATE", length = 100)),
			@AttributeOverride(name = "renewDate", column = @Column(name = "RENEW_DATE", length = 7)),
			@AttributeOverride(name = "isRnd", column = @Column(name = "IS_RND", length = 100)) })
	public EpharmaSystemInfoId getId() {
		return this.id;
	}

	public void setId(EpharmaSystemInfoId id) {
		this.id = id;
	}

}
