package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExceedDrugItemId generated by hbm2java
 */
@Embeddable
public class ExceedDrugItemId implements java.io.Serializable {

	private String phUnitNo;
	private String exceedNo;
	private String itemNo;
	private String batchNo;

	public ExceedDrugItemId() {
	}

	public ExceedDrugItemId(String phUnitNo, String exceedNo, String itemNo,
			String batchNo) {
		this.phUnitNo = phUnitNo;
		this.exceedNo = exceedNo;
		this.itemNo = itemNo;
		this.batchNo = batchNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "EXCEED_NO", nullable = false, length = 20)
	public String getExceedNo() {
		return this.exceedNo;
	}

	public void setExceedNo(String exceedNo) {
		this.exceedNo = exceedNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "BATCH_NO", nullable = false, length = 20)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExceedDrugItemId))
			return false;
		ExceedDrugItemId castOther = (ExceedDrugItemId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getExceedNo() == castOther.getExceedNo()) || (this
						.getExceedNo() != null
						&& castOther.getExceedNo() != null && this
						.getExceedNo().equals(castOther.getExceedNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null && castOther.getItemNo() != null && this
						.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getBatchNo() == castOther.getBatchNo()) || (this
						.getBatchNo() != null && castOther.getBatchNo() != null && this
						.getBatchNo().equals(castOther.getBatchNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37 * result
				+ (getExceedNo() == null ? 0 : this.getExceedNo().hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getBatchNo() == null ? 0 : this.getBatchNo().hashCode());
		return result;
	}

}
