package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exceed generated by hbm2java
 */
@Entity
@Table(name = "EXCEED")
public class Exceed implements java.io.Serializable {

	private ExceedId id;
	private PharmacyUnit pharmacyUnit;
	private Date exceedDate;
	private BigDecimal totalAmount;
	private BigDecimal printingStatus;
	private BigDecimal exceedIssueStatus;
	private String userId;
	private String userIp;
	private Set<ExceedDrugItem> exceedDrugItems = new HashSet<ExceedDrugItem>(0);

	public Exceed() {
	}

	public Exceed(ExceedId id, PharmacyUnit pharmacyUnit, Date exceedDate,
			BigDecimal totalAmount, BigDecimal printingStatus,
			BigDecimal exceedIssueStatus, String userId, String userIp) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.exceedDate = exceedDate;
		this.totalAmount = totalAmount;
		this.printingStatus = printingStatus;
		this.exceedIssueStatus = exceedIssueStatus;
		this.userId = userId;
		this.userIp = userIp;
	}

	public Exceed(ExceedId id, PharmacyUnit pharmacyUnit, Date exceedDate,
			BigDecimal totalAmount, BigDecimal printingStatus,
			BigDecimal exceedIssueStatus, String userId, String userIp,
			Set<ExceedDrugItem> exceedDrugItems) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.exceedDate = exceedDate;
		this.totalAmount = totalAmount;
		this.printingStatus = printingStatus;
		this.exceedIssueStatus = exceedIssueStatus;
		this.userId = userId;
		this.userIp = userIp;
		this.exceedDrugItems = exceedDrugItems;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "exceedNo", column = @Column(name = "EXCEED_NO", nullable = false, length = 20)) })
	public ExceedId getId() {
		return this.id;
	}

	public void setId(ExceedId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXCEED_DATE", nullable = false, length = 7)
	public Date getExceedDate() {
		return this.exceedDate;
	}

	public void setExceedDate(Date exceedDate) {
		this.exceedDate = exceedDate;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "EXCEED_ISSUE_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getExceedIssueStatus() {
		return this.exceedIssueStatus;
	}

	public void setExceedIssueStatus(BigDecimal exceedIssueStatus) {
		this.exceedIssueStatus = exceedIssueStatus;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exceed")
	public Set<ExceedDrugItem> getExceedDrugItems() {
		return this.exceedDrugItems;
	}

	public void setExceedDrugItems(Set<ExceedDrugItem> exceedDrugItems) {
		this.exceedDrugItems = exceedDrugItems;
	}

}
