package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ExceedDrugItem generated by hbm2java
 */
@Entity
@Table(name = "EXCEED_DRUG_ITEM")
public class ExceedDrugItem implements java.io.Serializable {

	private ExceedDrugItemId id;
	private Exceed exceed;
	private double quantity;
	private BigDecimal totalAmount;
	private String grnNo;

	public ExceedDrugItem() {
	}

	public ExceedDrugItem(ExceedDrugItemId id, Exceed exceed, double quantity,
			BigDecimal totalAmount) {
		this.id = id;
		this.exceed = exceed;
		this.quantity = quantity;
		this.totalAmount = totalAmount;
	}

	public ExceedDrugItem(ExceedDrugItemId id, Exceed exceed, double quantity,
			BigDecimal totalAmount, String grnNo) {
		this.id = id;
		this.exceed = exceed;
		this.quantity = quantity;
		this.totalAmount = totalAmount;
		this.grnNo = grnNo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "exceedNo", column = @Column(name = "EXCEED_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "batchNo", column = @Column(name = "BATCH_NO", nullable = false, length = 20)) })
	public ExceedDrugItemId getId() {
		return this.id;
	}

	public void setId(ExceedDrugItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PH_UNIT_NO", referencedColumnName = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "EXCEED_NO", referencedColumnName = "EXCEED_NO", nullable = false, insertable = false, updatable = false) })
	public Exceed getExceed() {
		return this.exceed;
	}

	public void setExceed(Exceed exceed) {
		this.exceed = exceed;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "GRN_NO", length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

}
