package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Grn generated by hbm2java
 */
@Entity
@Table(name = "GRN")
public class Grn implements java.io.Serializable {

	private GrnId id;
	private PurchaseOrder purchaseOrder;
	private Supplier supplier;
	private PharmacyUnit pharmacyUnit;
	private String supInvoiceNo;
	private BigDecimal totalAmount;
	private BigDecimal discountAmount;
	private BigDecimal taxAmount;
	private BigDecimal bonusAmount;
	private BigDecimal settleStatus;
	private BigDecimal grnPaymentType;
	private BigDecimal printingStatus;
	private String userId;
	private String userIp;
	private Date grnDate;
	private BigDecimal purchaseType;
	private BigDecimal currentPrice;
	private BigDecimal grnStatus;
	private BigDecimal issueOrder;
	private String throughUnit;
	private String remarks;
	private BigDecimal nbtValue;
	private Set<DrugItemUnitQuantity> drugItemUnitQuantities = new HashSet<DrugItemUnitQuantity>(
			0);
	private Set<GrnDrugItem> grnDrugItems = new HashSet<GrnDrugItem>(0);

	public Grn() {
	}

	public Grn(GrnId id, PurchaseOrder purchaseOrder, Supplier supplier,
			PharmacyUnit pharmacyUnit, String supInvoiceNo,
			BigDecimal totalAmount, BigDecimal settleStatus,
			BigDecimal grnPaymentType, BigDecimal printingStatus,
			String userId, String userIp, Date grnDate,
			BigDecimal purchaseType, BigDecimal currentPrice,
			BigDecimal grnStatus, BigDecimal issueOrder, String remarks) {
		this.id = id;
		this.purchaseOrder = purchaseOrder;
		this.supplier = supplier;
		this.pharmacyUnit = pharmacyUnit;
		this.supInvoiceNo = supInvoiceNo;
		this.totalAmount = totalAmount;
		this.settleStatus = settleStatus;
		this.grnPaymentType = grnPaymentType;
		this.printingStatus = printingStatus;
		this.userId = userId;
		this.userIp = userIp;
		this.grnDate = grnDate;
		this.purchaseType = purchaseType;
		this.currentPrice = currentPrice;
		this.grnStatus = grnStatus;
		this.issueOrder = issueOrder;
		this.remarks = remarks;
	}

	public Grn(GrnId id, PurchaseOrder purchaseOrder, Supplier supplier,
			PharmacyUnit pharmacyUnit, String supInvoiceNo,
			BigDecimal totalAmount, BigDecimal discountAmount,
			BigDecimal taxAmount, BigDecimal bonusAmount,
			BigDecimal settleStatus, BigDecimal grnPaymentType,
			BigDecimal printingStatus, String userId, String userIp,
			Date grnDate, BigDecimal purchaseType, BigDecimal currentPrice,
			BigDecimal grnStatus, BigDecimal issueOrder, String throughUnit,
			String remarks, BigDecimal nbtValue,
			Set<DrugItemUnitQuantity> drugItemUnitQuantities,
			Set<GrnDrugItem> grnDrugItems) {
		this.id = id;
		this.purchaseOrder = purchaseOrder;
		this.supplier = supplier;
		this.pharmacyUnit = pharmacyUnit;
		this.supInvoiceNo = supInvoiceNo;
		this.totalAmount = totalAmount;
		this.discountAmount = discountAmount;
		this.taxAmount = taxAmount;
		this.bonusAmount = bonusAmount;
		this.settleStatus = settleStatus;
		this.grnPaymentType = grnPaymentType;
		this.printingStatus = printingStatus;
		this.userId = userId;
		this.userIp = userIp;
		this.grnDate = grnDate;
		this.purchaseType = purchaseType;
		this.currentPrice = currentPrice;
		this.grnStatus = grnStatus;
		this.issueOrder = issueOrder;
		this.throughUnit = throughUnit;
		this.remarks = remarks;
		this.nbtValue = nbtValue;
		this.drugItemUnitQuantities = drugItemUnitQuantities;
		this.grnDrugItems = grnDrugItems;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)) })
	public GrnId getId() {
		return this.id;
	}

	public void setId(GrnId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PURCHASE_ORDER_NO", referencedColumnName = "PURCHASE_ORDER_NO", nullable = false),
			@JoinColumn(name = "UNIT_NO_PO", referencedColumnName = "PH_UNIT_NO", nullable = false) })
	public PurchaseOrder getPurchaseOrder() {
		return this.purchaseOrder;
	}

	public void setPurchaseOrder(PurchaseOrder purchaseOrder) {
		this.purchaseOrder = purchaseOrder;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SUP_NO", referencedColumnName = "SUP_NO", nullable = false),
			@JoinColumn(name = "UNIT_NO_SUP", referencedColumnName = "PH_UNIT_NO", nullable = false) })
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Column(name = "SUP_INVOICE_NO", nullable = false, length = 20)
	public String getSupInvoiceNo() {
		return this.supInvoiceNo;
	}

	public void setSupInvoiceNo(String supInvoiceNo) {
		this.supInvoiceNo = supInvoiceNo;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "DISCOUNT_AMOUNT", precision = 10)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "TAX_AMOUNT", precision = 10)
	public BigDecimal getTaxAmount() {
		return this.taxAmount;
	}

	public void setTaxAmount(BigDecimal taxAmount) {
		this.taxAmount = taxAmount;
	}

	@Column(name = "BONUS_AMOUNT", precision = 10)
	public BigDecimal getBonusAmount() {
		return this.bonusAmount;
	}

	public void setBonusAmount(BigDecimal bonusAmount) {
		this.bonusAmount = bonusAmount;
	}

	@Column(name = "SETTLE_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getSettleStatus() {
		return this.settleStatus;
	}

	public void setSettleStatus(BigDecimal settleStatus) {
		this.settleStatus = settleStatus;
	}

	@Column(name = "GRN_PAYMENT_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getGrnPaymentType() {
		return this.grnPaymentType;
	}

	public void setGrnPaymentType(BigDecimal grnPaymentType) {
		this.grnPaymentType = grnPaymentType;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GRN_DATE", nullable = false, length = 7)
	public Date getGrnDate() {
		return this.grnDate;
	}

	public void setGrnDate(Date grnDate) {
		this.grnDate = grnDate;
	}

	@Column(name = "PURCHASE_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPurchaseType() {
		return this.purchaseType;
	}

	public void setPurchaseType(BigDecimal purchaseType) {
		this.purchaseType = purchaseType;
	}

	@Column(name = "CURRENT_PRICE", nullable = false, precision = 12)
	public BigDecimal getCurrentPrice() {
		return this.currentPrice;
	}

	public void setCurrentPrice(BigDecimal currentPrice) {
		this.currentPrice = currentPrice;
	}

	@Column(name = "GRN_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getGrnStatus() {
		return this.grnStatus;
	}

	public void setGrnStatus(BigDecimal grnStatus) {
		this.grnStatus = grnStatus;
	}

	@Column(name = "ISSUE_ORDER", nullable = false, precision = 38, scale = 0)
	public BigDecimal getIssueOrder() {
		return this.issueOrder;
	}

	public void setIssueOrder(BigDecimal issueOrder) {
		this.issueOrder = issueOrder;
	}

	@Column(name = "THROUGH_UNIT", length = 20)
	public String getThroughUnit() {
		return this.throughUnit;
	}

	public void setThroughUnit(String throughUnit) {
		this.throughUnit = throughUnit;
	}

	@Column(name = "REMARKS", nullable = false, length = 200)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "NBT_VALUE", precision = 10)
	public BigDecimal getNbtValue() {
		return this.nbtValue;
	}

	public void setNbtValue(BigDecimal nbtValue) {
		this.nbtValue = nbtValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grn")
	public Set<DrugItemUnitQuantity> getDrugItemUnitQuantities() {
		return this.drugItemUnitQuantities;
	}

	public void setDrugItemUnitQuantities(
			Set<DrugItemUnitQuantity> drugItemUnitQuantities) {
		this.drugItemUnitQuantities = drugItemUnitQuantities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grn")
	public Set<GrnDrugItem> getGrnDrugItems() {
		return this.grnDrugItems;
	}

	public void setGrnDrugItems(Set<GrnDrugItem> grnDrugItems) {
		this.grnDrugItems = grnDrugItems;
	}

}
