package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GrnCancelId generated by hbm2java
 */
@Embeddable
public class GrnCancelId implements java.io.Serializable {

	private String phUnitNo;
	private String grnCancelNo;
	private String grnNo;

	public GrnCancelId() {
	}

	public GrnCancelId(String phUnitNo, String grnCancelNo, String grnNo) {
		this.phUnitNo = phUnitNo;
		this.grnCancelNo = grnCancelNo;
		this.grnNo = grnNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "GRN_CANCEL_NO", nullable = false, length = 20)
	public String getGrnCancelNo() {
		return this.grnCancelNo;
	}

	public void setGrnCancelNo(String grnCancelNo) {
		this.grnCancelNo = grnCancelNo;
	}

	@Column(name = "GRN_NO", nullable = false, length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrnCancelId))
			return false;
		GrnCancelId castOther = (GrnCancelId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getGrnCancelNo() == castOther.getGrnCancelNo()) || (this
						.getGrnCancelNo() != null
						&& castOther.getGrnCancelNo() != null && this
						.getGrnCancelNo().equals(castOther.getGrnCancelNo())))
				&& ((this.getGrnNo() == castOther.getGrnNo()) || (this
						.getGrnNo() != null && castOther.getGrnNo() != null && this
						.getGrnNo().equals(castOther.getGrnNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37
				* result
				+ (getGrnCancelNo() == null ? 0 : this.getGrnCancelNo()
						.hashCode());
		result = 37 * result
				+ (getGrnNo() == null ? 0 : this.getGrnNo().hashCode());
		return result;
	}

}
