package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GrnCancel generated by hbm2java
 */
@Entity
@Table(name = "GRN_CANCEL")
public class GrnCancel implements java.io.Serializable {

	private GrnCancelId id;
	private Date grnCancelDate;
	private BigDecimal printingStatus;
	private String userId;
	private String userIp;

	public GrnCancel() {
	}

	public GrnCancel(GrnCancelId id, Date grnCancelDate,
			BigDecimal printingStatus, String userId, String userIp) {
		this.id = id;
		this.grnCancelDate = grnCancelDate;
		this.printingStatus = printingStatus;
		this.userId = userId;
		this.userIp = userIp;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnCancelNo", column = @Column(name = "GRN_CANCEL_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)) })
	public GrnCancelId getId() {
		return this.id;
	}

	public void setId(GrnCancelId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GRN_CANCEL_DATE", nullable = false, length = 7)
	public Date getGrnCancelDate() {
		return this.grnCancelDate;
	}

	public void setGrnCancelDate(Date grnCancelDate) {
		this.grnCancelDate = grnCancelDate;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

}
