package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GrnDrugItem generated by hbm2java
 */
@Entity
@Table(name = "GRN_DRUG_ITEM")
public class GrnDrugItem implements java.io.Serializable {

	private GrnDrugItemId id;
	private Grn grn;
	private double quantity;
	private Date expDate;
	private BigDecimal totalAmount;
	private BigDecimal netAmount;
	private BigDecimal costPrice;
	private BigDecimal retailPrice;
	private BigDecimal packSize;
	private Double bonusQty;
	private BigDecimal billCost;
	private Date dayBefEx;

	public GrnDrugItem() {
	}

	public GrnDrugItem(GrnDrugItemId id, Grn grn, double quantity,
			Date expDate, BigDecimal totalAmount, BigDecimal netAmount,
			BigDecimal costPrice, BigDecimal retailPrice, Date dayBefEx) {
		this.id = id;
		this.grn = grn;
		this.quantity = quantity;
		this.expDate = expDate;
		this.totalAmount = totalAmount;
		this.netAmount = netAmount;
		this.costPrice = costPrice;
		this.retailPrice = retailPrice;
		this.dayBefEx = dayBefEx;
	}

	public GrnDrugItem(GrnDrugItemId id, Grn grn, double quantity,
			Date expDate, BigDecimal totalAmount, BigDecimal netAmount,
			BigDecimal costPrice, BigDecimal retailPrice, BigDecimal packSize,
			Double bonusQty, BigDecimal billCost, Date dayBefEx) {
		this.id = id;
		this.grn = grn;
		this.quantity = quantity;
		this.expDate = expDate;
		this.totalAmount = totalAmount;
		this.netAmount = netAmount;
		this.costPrice = costPrice;
		this.retailPrice = retailPrice;
		this.packSize = packSize;
		this.bonusQty = bonusQty;
		this.billCost = billCost;
		this.dayBefEx = dayBefEx;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "batchNo", column = @Column(name = "BATCH_NO", nullable = false, length = 20)) })
	public GrnDrugItemId getId() {
		return this.id;
	}

	public void setId(GrnDrugItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PH_UNIT_NO", referencedColumnName = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "GRN_NO", referencedColumnName = "GRN_NO", nullable = false, insertable = false, updatable = false) })
	public Grn getGrn() {
		return this.grn;
	}

	public void setGrn(Grn grn) {
		this.grn = grn;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXP_DATE", nullable = false, length = 7)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "NET_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(BigDecimal netAmount) {
		this.netAmount = netAmount;
	}

	@Column(name = "COST_PRICE", nullable = false, precision = 10)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "RETAIL_PRICE", nullable = false, precision = 10)
	public BigDecimal getRetailPrice() {
		return this.retailPrice;
	}

	public void setRetailPrice(BigDecimal retailPrice) {
		this.retailPrice = retailPrice;
	}

	@Column(name = "PACK_SIZE", precision = 22, scale = 0)
	public BigDecimal getPackSize() {
		return this.packSize;
	}

	public void setPackSize(BigDecimal packSize) {
		this.packSize = packSize;
	}

	@Column(name = "BONUS_QTY", precision = 22, scale = 0)
	public Double getBonusQty() {
		return this.bonusQty;
	}

	public void setBonusQty(Double bonusQty) {
		this.bonusQty = bonusQty;
	}

	@Column(name = "BILL_COST", precision = 10)
	public BigDecimal getBillCost() {
		return this.billCost;
	}

	public void setBillCost(BigDecimal billCost) {
		this.billCost = billCost;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DAY_BEF_EX", nullable = false, length = 7)
	public Date getDayBefEx() {
		return this.dayBefEx;
	}

	public void setDayBefEx(Date dayBefEx) {
		this.dayBefEx = dayBefEx;
	}

}
