package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GrnEdit generated by hbm2java
 */
@Entity
@Table(name = "GRN_EDIT")
public class GrnEdit implements java.io.Serializable {

	private GrnEditId id;
	private Date grnEditDate;
	private String userId;
	private String userIp;

	public GrnEdit() {
	}

	public GrnEdit(GrnEditId id, Date grnEditDate, String userId, String userIp) {
		this.id = id;
		this.grnEditDate = grnEditDate;
		this.userId = userId;
		this.userIp = userIp;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnEditNo", column = @Column(name = "GRN_EDIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)) })
	public GrnEditId getId() {
		return this.id;
	}

	public void setId(GrnEditId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GRN_EDIT_DATE", nullable = false, length = 7)
	public Date getGrnEditDate() {
		return this.grnEditDate;
	}

	public void setGrnEditDate(Date grnEditDate) {
		this.grnEditDate = grnEditDate;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

}
