package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * GrnEditDrugItem generated by hbm2java
 */
@Entity
@Table(name = "GRN_EDIT_DRUG_ITEM")
public class GrnEditDrugItem implements java.io.Serializable {

	private GrnEditDrugItemId id;
	private double quantity;
	private double lastQuantity;
	private BigDecimal costPrice;
	private double currBonusQty;
	private double bonusQty;

	public GrnEditDrugItem() {
	}

	public GrnEditDrugItem(GrnEditDrugItemId id, double quantity,
			double lastQuantity, BigDecimal costPrice, double currBonusQty,
			double bonusQty) {
		this.id = id;
		this.quantity = quantity;
		this.lastQuantity = lastQuantity;
		this.costPrice = costPrice;
		this.currBonusQty = currBonusQty;
		this.bonusQty = bonusQty;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnEditNo", column = @Column(name = "GRN_EDIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "batchNo", column = @Column(name = "BATCH_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)) })
	public GrnEditDrugItemId getId() {
		return this.id;
	}

	public void setId(GrnEditDrugItemId id) {
		this.id = id;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "LAST_QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getLastQuantity() {
		return this.lastQuantity;
	}

	public void setLastQuantity(double lastQuantity) {
		this.lastQuantity = lastQuantity;
	}

	@Column(name = "COST_PRICE", nullable = false, precision = 10)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "CURR_BONUS_QTY", nullable = false, precision = 22, scale = 0)
	public double getCurrBonusQty() {
		return this.currBonusQty;
	}

	public void setCurrBonusQty(double currBonusQty) {
		this.currBonusQty = currBonusQty;
	}

	@Column(name = "BONUS_QTY", nullable = false, precision = 22, scale = 0)
	public double getBonusQty() {
		return this.bonusQty;
	}

	public void setBonusQty(double bonusQty) {
		this.bonusQty = bonusQty;
	}

}
