package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GrnEditDrugItemId generated by hbm2java
 */
@Embeddable
public class GrnEditDrugItemId implements java.io.Serializable {

	private String phUnitNo;
	private String grnEditNo;
	private String itemNo;
	private String batchNo;
	private String grnNo;

	public GrnEditDrugItemId() {
	}

	public GrnEditDrugItemId(String phUnitNo, String grnEditNo, String itemNo,
			String batchNo, String grnNo) {
		this.phUnitNo = phUnitNo;
		this.grnEditNo = grnEditNo;
		this.itemNo = itemNo;
		this.batchNo = batchNo;
		this.grnNo = grnNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "GRN_EDIT_NO", nullable = false, length = 20)
	public String getGrnEditNo() {
		return this.grnEditNo;
	}

	public void setGrnEditNo(String grnEditNo) {
		this.grnEditNo = grnEditNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "BATCH_NO", nullable = false, length = 20)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Column(name = "GRN_NO", nullable = false, length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GrnEditDrugItemId))
			return false;
		GrnEditDrugItemId castOther = (GrnEditDrugItemId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getGrnEditNo() == castOther.getGrnEditNo()) || (this
						.getGrnEditNo() != null
						&& castOther.getGrnEditNo() != null && this
						.getGrnEditNo().equals(castOther.getGrnEditNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null && castOther.getItemNo() != null && this
						.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getBatchNo() == castOther.getBatchNo()) || (this
						.getBatchNo() != null && castOther.getBatchNo() != null && this
						.getBatchNo().equals(castOther.getBatchNo())))
				&& ((this.getGrnNo() == castOther.getGrnNo()) || (this
						.getGrnNo() != null && castOther.getGrnNo() != null && this
						.getGrnNo().equals(castOther.getGrnNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37 * result
				+ (getGrnEditNo() == null ? 0 : this.getGrnEditNo().hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getBatchNo() == null ? 0 : this.getBatchNo().hashCode());
		result = 37 * result
				+ (getGrnNo() == null ? 0 : this.getGrnNo().hashCode());
		return result;
	}

}
