package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GrnTempItem generated by hbm2java
 */
@Entity
@Table(name = "GRN_TEMP_ITEM")
public class GrnTempItem implements java.io.Serializable {

	private GrnTempItemId id;
	private BigDecimal pkt;
	private BigDecimal unit;
	private BigDecimal BQty;
	private BigDecimal costPrice;
	private BigDecimal rerailPrice;
	private String batchNo;
	private Date expDate;
	private BigDecimal discount;
	private BigDecimal tax;
	private String userId;
	private Date txnDate;
	private BigDecimal status;
	private BigDecimal newCost;
	private BigDecimal newRetail;

	public GrnTempItem() {
	}

	public GrnTempItem(GrnTempItemId id, BigDecimal pkt, BigDecimal unit,
			BigDecimal BQty, BigDecimal costPrice, BigDecimal rerailPrice,
			String batchNo, Date expDate, BigDecimal discount, BigDecimal tax,
			String userId, Date txnDate, BigDecimal status, BigDecimal newCost,
			BigDecimal newRetail) {
		this.id = id;
		this.pkt = pkt;
		this.unit = unit;
		this.BQty = BQty;
		this.costPrice = costPrice;
		this.rerailPrice = rerailPrice;
		this.batchNo = batchNo;
		this.expDate = expDate;
		this.discount = discount;
		this.tax = tax;
		this.userId = userId;
		this.txnDate = txnDate;
		this.status = status;
		this.newCost = newCost;
		this.newRetail = newRetail;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "poNumber", column = @Column(name = "PO_NUMBER", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)) })
	public GrnTempItemId getId() {
		return this.id;
	}

	public void setId(GrnTempItemId id) {
		this.id = id;
	}

	@Column(name = "PKT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getPkt() {
		return this.pkt;
	}

	public void setPkt(BigDecimal pkt) {
		this.pkt = pkt;
	}

	@Column(name = "UNIT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getUnit() {
		return this.unit;
	}

	public void setUnit(BigDecimal unit) {
		this.unit = unit;
	}

	@Column(name = "B_QTY", nullable = false, precision = 22, scale = 0)
	public BigDecimal getBQty() {
		return this.BQty;
	}

	public void setBQty(BigDecimal BQty) {
		this.BQty = BQty;
	}

	@Column(name = "COST_PRICE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "RERAIL_PRICE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRerailPrice() {
		return this.rerailPrice;
	}

	public void setRerailPrice(BigDecimal rerailPrice) {
		this.rerailPrice = rerailPrice;
	}

	@Column(name = "BATCH_NO", nullable = false, length = 20)
	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXP_DATE", nullable = false, length = 7)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "DISCOUNT", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "TAX", nullable = false, precision = 22, scale = 0)
	public BigDecimal getTax() {
		return this.tax;
	}

	public void setTax(BigDecimal tax) {
		this.tax = tax;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TXN_DATE", nullable = false, length = 7)
	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	@Column(name = "STATUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Column(name = "NEW_COST", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNewCost() {
		return this.newCost;
	}

	public void setNewCost(BigDecimal newCost) {
		this.newCost = newCost;
	}

	@Column(name = "NEW_RETAIL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getNewRetail() {
		return this.newRetail;
	}

	public void setNewRetail(BigDecimal newRetail) {
		this.newRetail = newRetail;
	}

}
