package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IssuePharmacyUnit generated by hbm2java
 */
@Entity
@Table(name = "ISSUE_PHARMACY_UNIT")
public class IssuePharmacyUnit implements java.io.Serializable {

	private IssuePharmacyUnitId id;
	private String orderNo;
	private Date issueDate;
	private BigDecimal issueStatus;
	private BigDecimal printingStatus;
	private String userId;
	private String userIp;
	private BigDecimal completeStatus;

	public IssuePharmacyUnit() {
	}

	public IssuePharmacyUnit(IssuePharmacyUnitId id, String orderNo,
			Date issueDate, BigDecimal issueStatus, BigDecimal printingStatus,
			String userId, String userIp, BigDecimal completeStatus) {
		this.id = id;
		this.orderNo = orderNo;
		this.issueDate = issueDate;
		this.issueStatus = issueStatus;
		this.printingStatus = printingStatus;
		this.userId = userId;
		this.userIp = userIp;
		this.completeStatus = completeStatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "issueNo", column = @Column(name = "ISSUE_NO", nullable = false, length = 20)) })
	public IssuePharmacyUnitId getId() {
		return this.id;
	}

	public void setId(IssuePharmacyUnitId id) {
		this.id = id;
	}

	@Column(name = "ORDER_NO", nullable = false, length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ISSUE_DATE", nullable = false, length = 7)
	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "ISSUE_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getIssueStatus() {
		return this.issueStatus;
	}

	public void setIssueStatus(BigDecimal issueStatus) {
		this.issueStatus = issueStatus;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "COMPLETE_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getCompleteStatus() {
		return this.completeStatus;
	}

	public void setCompleteStatus(BigDecimal completeStatus) {
		this.completeStatus = completeStatus;
	}

}
