package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IssuePharmacyUnitId generated by hbm2java
 */
@Embeddable
public class IssuePharmacyUnitId implements java.io.Serializable {

	private String phUnitNo;
	private String issueNo;

	public IssuePharmacyUnitId() {
	}

	public IssuePharmacyUnitId(String phUnitNo, String issueNo) {
		this.phUnitNo = phUnitNo;
		this.issueNo = issueNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "ISSUE_NO", nullable = false, length = 20)
	public String getIssueNo() {
		return this.issueNo;
	}

	public void setIssueNo(String issueNo) {
		this.issueNo = issueNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IssuePharmacyUnitId))
			return false;
		IssuePharmacyUnitId castOther = (IssuePharmacyUnitId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getIssueNo() == castOther.getIssueNo()) || (this
						.getIssueNo() != null && castOther.getIssueNo() != null && this
						.getIssueNo().equals(castOther.getIssueNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37 * result
				+ (getIssueNo() == null ? 0 : this.getIssueNo().hashCode());
		return result;
	}

}
