package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IssuePharmacyUnitAccept generated by hbm2java
 */
@Entity
@Table(name = "ISSUE_PHARMACY_UNIT_ACCEPT")
public class IssuePharmacyUnitAccept implements java.io.Serializable {

	private IssuePharmacyUnitAcceptId id;
	private String fromUnitNo;
	private BigDecimal acceptType;
	private Date acceptDate;
	private String userId;
	private String userIp;

	public IssuePharmacyUnitAccept() {
	}

	public IssuePharmacyUnitAccept(IssuePharmacyUnitAcceptId id,
			String fromUnitNo, BigDecimal acceptType, Date acceptDate,
			String userId, String userIp) {
		this.id = id;
		this.fromUnitNo = fromUnitNo;
		this.acceptType = acceptType;
		this.acceptDate = acceptDate;
		this.userId = userId;
		this.userIp = userIp;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "acceptNo", column = @Column(name = "ACCEPT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "issueReturnNo", column = @Column(name = "ISSUE_RETURN_NO", nullable = false, length = 20)) })
	public IssuePharmacyUnitAcceptId getId() {
		return this.id;
	}

	public void setId(IssuePharmacyUnitAcceptId id) {
		this.id = id;
	}

	@Column(name = "FROM_UNIT_NO", nullable = false, length = 20)
	public String getFromUnitNo() {
		return this.fromUnitNo;
	}

	public void setFromUnitNo(String fromUnitNo) {
		this.fromUnitNo = fromUnitNo;
	}

	@Column(name = "ACCEPT_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getAcceptType() {
		return this.acceptType;
	}

	public void setAcceptType(BigDecimal acceptType) {
		this.acceptType = acceptType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ACCEPT_DATE", nullable = false, length = 7)
	public Date getAcceptDate() {
		return this.acceptDate;
	}

	public void setAcceptDate(Date acceptDate) {
		this.acceptDate = acceptDate;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

}
