package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IssuePharmacyReturnItem generated by hbm2java
 */
@Entity
@Table(name = "ISSUE_PHARMACY_RETURN_ITEM")
public class IssuePharmacyReturnItem implements java.io.Serializable {

	private IssuePharmacyReturnItemId id;
	private double quantity;
	private String issueNo;
	private String issuedUnitNo;

	public IssuePharmacyReturnItem() {
	}

	public IssuePharmacyReturnItem(IssuePharmacyReturnItemId id,
			double quantity, String issueNo, String issuedUnitNo) {
		this.id = id;
		this.quantity = quantity;
		this.issueNo = issueNo;
		this.issuedUnitNo = issuedUnitNo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "returnNo", column = @Column(name = "RETURN_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)) })
	public IssuePharmacyReturnItemId getId() {
		return this.id;
	}

	public void setId(IssuePharmacyReturnItemId id) {
		this.id = id;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "ISSUE_NO", nullable = false, length = 20)
	public String getIssueNo() {
		return this.issueNo;
	}

	public void setIssueNo(String issueNo) {
		this.issueNo = issueNo;
	}

	@Column(name = "ISSUED_UNIT_NO", nullable = false, length = 20)
	public String getIssuedUnitNo() {
		return this.issuedUnitNo;
	}

	public void setIssuedUnitNo(String issuedUnitNo) {
		this.issuedUnitNo = issuedUnitNo;
	}

}
