package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IssuePharmacyUnitAcceptId generated by hbm2java
 */
@Embeddable
public class IssuePharmacyUnitAcceptId implements java.io.Serializable {

	private String phUnitNo;
	private String acceptNo;
	private String issueReturnNo;

	public IssuePharmacyUnitAcceptId() {
	}

	public IssuePharmacyUnitAcceptId(String phUnitNo, String acceptNo,
			String issueReturnNo) {
		this.phUnitNo = phUnitNo;
		this.acceptNo = acceptNo;
		this.issueReturnNo = issueReturnNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "ACCEPT_NO", nullable = false, length = 20)
	public String getAcceptNo() {
		return this.acceptNo;
	}

	public void setAcceptNo(String acceptNo) {
		this.acceptNo = acceptNo;
	}

	@Column(name = "ISSUE_RETURN_NO", nullable = false, length = 20)
	public String getIssueReturnNo() {
		return this.issueReturnNo;
	}

	public void setIssueReturnNo(String issueReturnNo) {
		this.issueReturnNo = issueReturnNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IssuePharmacyUnitAcceptId))
			return false;
		IssuePharmacyUnitAcceptId castOther = (IssuePharmacyUnitAcceptId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getAcceptNo() == castOther.getAcceptNo()) || (this
						.getAcceptNo() != null
						&& castOther.getAcceptNo() != null && this
						.getAcceptNo().equals(castOther.getAcceptNo())))
				&& ((this.getIssueReturnNo() == castOther.getIssueReturnNo()) || (this
						.getIssueReturnNo() != null
						&& castOther.getIssueReturnNo() != null && this
						.getIssueReturnNo()
						.equals(castOther.getIssueReturnNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37 * result
				+ (getAcceptNo() == null ? 0 : this.getAcceptNo().hashCode());
		result = 37
				* result
				+ (getIssueReturnNo() == null ? 0 : this.getIssueReturnNo()
						.hashCode());
		return result;
	}

}
