package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IssueToUnitCancelId generated by hbm2java
 */
@Embeddable
public class IssueToUnitCancelId implements java.io.Serializable {

	private String phUnitNo;
	private String issueRetunrNo;
	private String issueToUnitCancelNo;

	public IssueToUnitCancelId() {
	}

	public IssueToUnitCancelId(String phUnitNo, String issueRetunrNo,
			String issueToUnitCancelNo) {
		this.phUnitNo = phUnitNo;
		this.issueRetunrNo = issueRetunrNo;
		this.issueToUnitCancelNo = issueToUnitCancelNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "ISSUE_RETUNR_NO", nullable = false, length = 20)
	public String getIssueRetunrNo() {
		return this.issueRetunrNo;
	}

	public void setIssueRetunrNo(String issueRetunrNo) {
		this.issueRetunrNo = issueRetunrNo;
	}

	@Column(name = "ISSUE_TO_UNIT_CANCEL_NO", nullable = false, length = 20)
	public String getIssueToUnitCancelNo() {
		return this.issueToUnitCancelNo;
	}

	public void setIssueToUnitCancelNo(String issueToUnitCancelNo) {
		this.issueToUnitCancelNo = issueToUnitCancelNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IssueToUnitCancelId))
			return false;
		IssueToUnitCancelId castOther = (IssueToUnitCancelId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getIssueRetunrNo() == castOther.getIssueRetunrNo()) || (this
						.getIssueRetunrNo() != null
						&& castOther.getIssueRetunrNo() != null && this
						.getIssueRetunrNo()
						.equals(castOther.getIssueRetunrNo())))
				&& ((this.getIssueToUnitCancelNo() == castOther
						.getIssueToUnitCancelNo()) || (this
						.getIssueToUnitCancelNo() != null
						&& castOther.getIssueToUnitCancelNo() != null && this
						.getIssueToUnitCancelNo().equals(
								castOther.getIssueToUnitCancelNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37
				* result
				+ (getIssueRetunrNo() == null ? 0 : this.getIssueRetunrNo()
						.hashCode());
		result = 37
				* result
				+ (getIssueToUnitCancelNo() == null ? 0 : this
						.getIssueToUnitCancelNo().hashCode());
		return result;
	}

}
