package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IssuePharmacyConsumptionId generated by hbm2java
 */
@Embeddable
public class IssuePharmacyConsumptionId implements java.io.Serializable {

	private String pharmacyUnit1;
	private String pharmacyUnit2;

	public IssuePharmacyConsumptionId() {
	}

	public IssuePharmacyConsumptionId(String pharmacyUnit1, String pharmacyUnit2) {
		this.pharmacyUnit1 = pharmacyUnit1;
		this.pharmacyUnit2 = pharmacyUnit2;
	}

	@Column(name = "PHARMACY_UNIT1", nullable = false, length = 20)
	public String getPharmacyUnit1() {
		return this.pharmacyUnit1;
	}

	public void setPharmacyUnit1(String pharmacyUnit1) {
		this.pharmacyUnit1 = pharmacyUnit1;
	}

	@Column(name = "PHARMACY_UNIT2", nullable = false, length = 20)
	public String getPharmacyUnit2() {
		return this.pharmacyUnit2;
	}

	public void setPharmacyUnit2(String pharmacyUnit2) {
		this.pharmacyUnit2 = pharmacyUnit2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IssuePharmacyConsumptionId))
			return false;
		IssuePharmacyConsumptionId castOther = (IssuePharmacyConsumptionId) other;

		return ((this.getPharmacyUnit1() == castOther.getPharmacyUnit1()) || (this
				.getPharmacyUnit1() != null
				&& castOther.getPharmacyUnit1() != null && this
				.getPharmacyUnit1().equals(castOther.getPharmacyUnit1())))
				&& ((this.getPharmacyUnit2() == castOther.getPharmacyUnit2()) || (this
						.getPharmacyUnit2() != null
						&& castOther.getPharmacyUnit2() != null && this
						.getPharmacyUnit2()
						.equals(castOther.getPharmacyUnit2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPharmacyUnit1() == null ? 0 : this.getPharmacyUnit1()
						.hashCode());
		result = 37
				* result
				+ (getPharmacyUnit2() == null ? 0 : this.getPharmacyUnit2()
						.hashCode());
		return result;
	}

}
