package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IssueToUnitCancel generated by hbm2java
 */
@Entity
@Table(name = "ISSUE_TO_UNIT_CANCEL")
public class IssueToUnitCancel implements java.io.Serializable {

	private IssueToUnitCancelId id;
	private BigDecimal issueType;
	private Date issueToUnitCancelDate;
	private BigDecimal printingStatus;
	private String userIp;
	private String userId;

	public IssueToUnitCancel() {
	}

	public IssueToUnitCancel(IssueToUnitCancelId id, BigDecimal issueType,
			Date issueToUnitCancelDate, BigDecimal printingStatus,
			String userIp, String userId) {
		this.id = id;
		this.issueType = issueType;
		this.issueToUnitCancelDate = issueToUnitCancelDate;
		this.printingStatus = printingStatus;
		this.userIp = userIp;
		this.userId = userId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "issueRetunrNo", column = @Column(name = "ISSUE_RETUNR_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "issueToUnitCancelNo", column = @Column(name = "ISSUE_TO_UNIT_CANCEL_NO", nullable = false, length = 20)) })
	public IssueToUnitCancelId getId() {
		return this.id;
	}

	public void setId(IssueToUnitCancelId id) {
		this.id = id;
	}

	@Column(name = "ISSUE_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getIssueType() {
		return this.issueType;
	}

	public void setIssueType(BigDecimal issueType) {
		this.issueType = issueType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ISSUE_TO_UNIT_CANCEL_DATE", nullable = false, length = 7)
	public Date getIssueToUnitCancelDate() {
		return this.issueToUnitCancelDate;
	}

	public void setIssueToUnitCancelDate(Date issueToUnitCancelDate) {
		this.issueToUnitCancelDate = issueToUnitCancelDate;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
