package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IssuePharmacyReturn generated by hbm2java
 */
@Entity
@Table(name = "ISSUE_PHARMACY_RETURN")
public class IssuePharmacyReturn implements java.io.Serializable {

	private IssuePharmacyReturnId id;
	private String issueNo;
	private Date returnDate;
	private BigDecimal printingStatus;
	private String userId;
	private String userIp;
	private BigDecimal returnStatus;
	private String issuedUnitNo;

	public IssuePharmacyReturn() {
	}

	public IssuePharmacyReturn(IssuePharmacyReturnId id, String issueNo,
			Date returnDate, BigDecimal printingStatus, String userId,
			String userIp, BigDecimal returnStatus, String issuedUnitNo) {
		this.id = id;
		this.issueNo = issueNo;
		this.returnDate = returnDate;
		this.printingStatus = printingStatus;
		this.userId = userId;
		this.userIp = userIp;
		this.returnStatus = returnStatus;
		this.issuedUnitNo = issuedUnitNo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "returnNo", column = @Column(name = "RETURN_NO", nullable = false, length = 20)) })
	public IssuePharmacyReturnId getId() {
		return this.id;
	}

	public void setId(IssuePharmacyReturnId id) {
		this.id = id;
	}

	@Column(name = "ISSUE_NO", nullable = false, length = 20)
	public String getIssueNo() {
		return this.issueNo;
	}

	public void setIssueNo(String issueNo) {
		this.issueNo = issueNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RETURN_DATE", nullable = false, length = 7)
	public Date getReturnDate() {
		return this.returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "RETURN_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getReturnStatus() {
		return this.returnStatus;
	}

	public void setReturnStatus(BigDecimal returnStatus) {
		this.returnStatus = returnStatus;
	}

	@Column(name = "ISSUED_UNIT_NO", nullable = false, length = 20)
	public String getIssuedUnitNo() {
		return this.issuedUnitNo;
	}

	public void setIssuedUnitNo(String issuedUnitNo) {
		this.issuedUnitNo = issuedUnitNo;
	}

}
