package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemPrice generated by hbm2java
 */
@Entity
@Table(name = "ITEM_PRICE")
public class ItemPrice implements java.io.Serializable {

	private ItemPriceId id;
	private PharmacyUnit pharmacyUnit;
	private BigDecimal costPrice;
	private BigDecimal lastCostPrice;
	private BigDecimal retailPrice;
	private BigDecimal weightedAveragePrice;
	private BigDecimal last2CostPrice;
	private BigDecimal lastRetailPrice;
	private BigDecimal last2RetailPrice;

	public ItemPrice() {
	}

	public ItemPrice(ItemPriceId id, PharmacyUnit pharmacyUnit,
			BigDecimal costPrice, BigDecimal lastCostPrice,
			BigDecimal retailPrice, BigDecimal weightedAveragePrice) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.costPrice = costPrice;
		this.lastCostPrice = lastCostPrice;
		this.retailPrice = retailPrice;
		this.weightedAveragePrice = weightedAveragePrice;
	}

	public ItemPrice(ItemPriceId id, PharmacyUnit pharmacyUnit,
			BigDecimal costPrice, BigDecimal lastCostPrice,
			BigDecimal retailPrice, BigDecimal weightedAveragePrice,
			BigDecimal last2CostPrice, BigDecimal lastRetailPrice,
			BigDecimal last2RetailPrice) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.costPrice = costPrice;
		this.lastCostPrice = lastCostPrice;
		this.retailPrice = retailPrice;
		this.weightedAveragePrice = weightedAveragePrice;
		this.last2CostPrice = last2CostPrice;
		this.lastRetailPrice = lastRetailPrice;
		this.last2RetailPrice = last2RetailPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)) })
	public ItemPriceId getId() {
		return this.id;
	}

	public void setId(ItemPriceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Column(name = "COST_PRICE", nullable = false, precision = 10)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "LAST_COST_PRICE", nullable = false, precision = 10)
	public BigDecimal getLastCostPrice() {
		return this.lastCostPrice;
	}

	public void setLastCostPrice(BigDecimal lastCostPrice) {
		this.lastCostPrice = lastCostPrice;
	}

	@Column(name = "RETAIL_PRICE", nullable = false, precision = 10)
	public BigDecimal getRetailPrice() {
		return this.retailPrice;
	}

	public void setRetailPrice(BigDecimal retailPrice) {
		this.retailPrice = retailPrice;
	}

	@Column(name = "WEIGHTED_AVERAGE_PRICE", nullable = false, precision = 10)
	public BigDecimal getWeightedAveragePrice() {
		return this.weightedAveragePrice;
	}

	public void setWeightedAveragePrice(BigDecimal weightedAveragePrice) {
		this.weightedAveragePrice = weightedAveragePrice;
	}

	@Column(name = "LAST2_COST_PRICE", precision = 10)
	public BigDecimal getLast2CostPrice() {
		return this.last2CostPrice;
	}

	public void setLast2CostPrice(BigDecimal last2CostPrice) {
		this.last2CostPrice = last2CostPrice;
	}

	@Column(name = "LAST_RETAIL_PRICE", precision = 10)
	public BigDecimal getLastRetailPrice() {
		return this.lastRetailPrice;
	}

	public void setLastRetailPrice(BigDecimal lastRetailPrice) {
		this.lastRetailPrice = lastRetailPrice;
	}

	@Column(name = "LAST2_RETAIL_PRICE", precision = 10)
	public BigDecimal getLast2RetailPrice() {
		return this.last2RetailPrice;
	}

	public void setLast2RetailPrice(BigDecimal last2RetailPrice) {
		this.last2RetailPrice = last2RetailPrice;
	}

}
