package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemConsumptionId generated by hbm2java
 */
@Embeddable
public class ItemConsumptionId implements java.io.Serializable {

	private String itemConsumptionNo;
	private String phUnitNo;

	public ItemConsumptionId() {
	}

	public ItemConsumptionId(String itemConsumptionNo, String phUnitNo) {
		this.itemConsumptionNo = itemConsumptionNo;
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "ITEM_CONSUMPTION_NO", nullable = false, length = 26)
	public String getItemConsumptionNo() {
		return this.itemConsumptionNo;
	}

	public void setItemConsumptionNo(String itemConsumptionNo) {
		this.itemConsumptionNo = itemConsumptionNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemConsumptionId))
			return false;
		ItemConsumptionId castOther = (ItemConsumptionId) other;

		return ((this.getItemConsumptionNo() == castOther
				.getItemConsumptionNo()) || (this.getItemConsumptionNo() != null
				&& castOther.getItemConsumptionNo() != null && this
				.getItemConsumptionNo()
				.equals(castOther.getItemConsumptionNo())))
				&& ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
						.getPhUnitNo() != null
						&& castOther.getPhUnitNo() != null && this
						.getPhUnitNo().equals(castOther.getPhUnitNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getItemConsumptionNo() == null ? 0 : this
						.getItemConsumptionNo().hashCode());
		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		return result;
	}

}
