package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemConsumption generated by hbm2java
 */
@Entity
@Table(name = "ITEM_CONSUMPTION")
public class ItemConsumption implements java.io.Serializable {

	private ItemConsumptionId id;
	private PharmacyUnit pharmacyUnit;
	private String itemNo;
	private String txnNo;
	private Date txnDate;
	private BigDecimal txnType;
	private double quantity;
	private BigDecimal totalAmount;
	private long issueStatus;
	private BigDecimal totalWeightAmount;

	public ItemConsumption() {
	}

	public ItemConsumption(ItemConsumptionId id, PharmacyUnit pharmacyUnit,
			String itemNo, String txnNo, Date txnDate, BigDecimal txnType,
			double quantity, BigDecimal totalAmount, long issueStatus,
			BigDecimal totalWeightAmount) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.itemNo = itemNo;
		this.txnNo = txnNo;
		this.txnDate = txnDate;
		this.txnType = txnType;
		this.quantity = quantity;
		this.totalAmount = totalAmount;
		this.issueStatus = issueStatus;
		this.totalWeightAmount = totalWeightAmount;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "itemConsumptionNo", column = @Column(name = "ITEM_CONSUMPTION_NO", nullable = false, length = 26)),
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)) })
	public ItemConsumptionId getId() {
		return this.id;
	}

	public void setId(ItemConsumptionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "TXN_NO", nullable = false, length = 20)
	public String getTxnNo() {
		return this.txnNo;
	}

	public void setTxnNo(String txnNo) {
		this.txnNo = txnNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TXN_DATE", nullable = false, length = 7)
	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	@Column(name = "TXN_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getTxnType() {
		return this.txnType;
	}

	public void setTxnType(BigDecimal txnType) {
		this.txnType = txnType;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "ISSUE_STATUS", nullable = false, precision = 10, scale = 0)
	public long getIssueStatus() {
		return this.issueStatus;
	}

	public void setIssueStatus(long issueStatus) {
		this.issueStatus = issueStatus;
	}

	@Column(name = "TOTAL_WEIGHT_AMOUNT", nullable = false, precision = 38)
	public BigDecimal getTotalWeightAmount() {
		return this.totalWeightAmount;
	}

	public void setTotalWeightAmount(BigDecimal totalWeightAmount) {
		this.totalWeightAmount = totalWeightAmount;
	}

}
