package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoyalityCards generated by hbm2java
 */
@Entity
@Table(name = "LOYALITY_CARDS")
public class LoyalityCards implements java.io.Serializable {

	private String cardNo;
	private String cardName;
	private BigDecimal cardType;
	private BigDecimal status;
	private Date regDate;
	private String userIp;
	private String userId;
	private Double minLimit;
	private Double maxLimit;
	private Set<CustPointSpends> custPointSpendses = new HashSet<CustPointSpends>(
			0);
	private Set<CardRates> cardRateses = new HashSet<CardRates>(0);

	public LoyalityCards() {
	}

	public LoyalityCards(String cardNo, String cardName, BigDecimal cardType,
			BigDecimal status, Date regDate, String userIp, String userId) {
		this.cardNo = cardNo;
		this.cardName = cardName;
		this.cardType = cardType;
		this.status = status;
		this.regDate = regDate;
		this.userIp = userIp;
		this.userId = userId;
	}

	public LoyalityCards(String cardNo, String cardName, BigDecimal cardType,
			BigDecimal status, Date regDate, String userIp, String userId,
			Double minLimit, Double maxLimit,
			Set<CustPointSpends> custPointSpendses, Set<CardRates> cardRateses) {
		this.cardNo = cardNo;
		this.cardName = cardName;
		this.cardType = cardType;
		this.status = status;
		this.regDate = regDate;
		this.userIp = userIp;
		this.userId = userId;
		this.minLimit = minLimit;
		this.maxLimit = maxLimit;
		this.custPointSpendses = custPointSpendses;
		this.cardRateses = cardRateses;
	}

	@Id
	@Column(name = "CARD_NO", unique = true, nullable = false, length = 10)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "CARD_NAME", nullable = false, length = 50)
	public String getCardName() {
		return this.cardName;
	}

	public void setCardName(String cardName) {
		this.cardName = cardName;
	}

	@Column(name = "CARD_TYPE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCardType() {
		return this.cardType;
	}

	public void setCardType(BigDecimal cardType) {
		this.cardType = cardType;
	}

	@Column(name = "STATUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REG_DATE", nullable = false, length = 7)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "MIN_LIMIT", precision = 126, scale = 0)
	public Double getMinLimit() {
		return this.minLimit;
	}

	public void setMinLimit(Double minLimit) {
		this.minLimit = minLimit;
	}

	@Column(name = "MAX_LIMIT", precision = 126, scale = 0)
	public Double getMaxLimit() {
		return this.maxLimit;
	}

	public void setMaxLimit(Double maxLimit) {
		this.maxLimit = maxLimit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loyalityCards")
	public Set<CustPointSpends> getCustPointSpendses() {
		return this.custPointSpendses;
	}

	public void setCustPointSpendses(Set<CustPointSpends> custPointSpendses) {
		this.custPointSpendses = custPointSpendses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loyalityCards")
	public Set<CardRates> getCardRateses() {
		return this.cardRateses;
	}

	public void setCardRateses(Set<CardRates> cardRateses) {
		this.cardRateses = cardRateses;
	}

}
