package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MonthlyItemConsumptionId generated by hbm2java
 */
@Embeddable
public class MonthlyItemConsumptionId implements java.io.Serializable {

	private String itemNo;
	private String unitNo;

	public MonthlyItemConsumptionId() {
	}

	public MonthlyItemConsumptionId(String itemNo, String unitNo) {
		this.itemNo = itemNo;
		this.unitNo = unitNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "UNIT_NO", nullable = false, length = 20)
	public String getUnitNo() {
		return this.unitNo;
	}

	public void setUnitNo(String unitNo) {
		this.unitNo = unitNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MonthlyItemConsumptionId))
			return false;
		MonthlyItemConsumptionId castOther = (MonthlyItemConsumptionId) other;

		return ((this.getItemNo() == castOther.getItemNo()) || (this
				.getItemNo() != null && castOther.getItemNo() != null && this
				.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getUnitNo() == castOther.getUnitNo()) || (this
						.getUnitNo() != null && castOther.getUnitNo() != null && this
						.getUnitNo().equals(castOther.getUnitNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getUnitNo() == null ? 0 : this.getUnitNo().hashCode());
		return result;
	}

}
