package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MonthlyItemConsumption generated by hbm2java
 */
@Entity
@Table(name = "MONTHLY_ITEM_CONSUMPTION")
public class MonthlyItemConsumption implements java.io.Serializable {

	private MonthlyItemConsumptionId id;
	private double consumption;
	private Date calculatedDate;

	public MonthlyItemConsumption() {
	}

	public MonthlyItemConsumption(MonthlyItemConsumptionId id,
			double consumption, Date calculatedDate) {
		this.id = id;
		this.consumption = consumption;
		this.calculatedDate = calculatedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "unitNo", column = @Column(name = "UNIT_NO", nullable = false, length = 20)) })
	public MonthlyItemConsumptionId getId() {
		return this.id;
	}

	public void setId(MonthlyItemConsumptionId id) {
		this.id = id;
	}

	@Column(name = "CONSUMPTION", nullable = false, precision = 126, scale = 0)
	public double getConsumption() {
		return this.consumption;
	}

	public void setConsumption(double consumption) {
		this.consumption = consumption;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALCULATED_DATE", nullable = false, length = 7)
	public Date getCalculatedDate() {
		return this.calculatedDate;
	}

	public void setCalculatedDate(Date calculatedDate) {
		this.calculatedDate = calculatedDate;
	}

}
