package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OutdoorIssueItemId generated by hbm2java
 */
@Embeddable
public class OutdoorIssueItemId implements java.io.Serializable {

	private String outdoorInvoiceNo;
	private String phUnitNo;
	private String itemNo;
	private String grnNo;
	private String directionNo;

	public OutdoorIssueItemId() {
	}

	public OutdoorIssueItemId(String outdoorInvoiceNo, String phUnitNo,
			String itemNo, String grnNo, String directionNo) {
		this.outdoorInvoiceNo = outdoorInvoiceNo;
		this.phUnitNo = phUnitNo;
		this.itemNo = itemNo;
		this.grnNo = grnNo;
		this.directionNo = directionNo;
	}

	@Column(name = "OUTDOOR_INVOICE_NO", nullable = false, length = 20)
	public String getOutdoorInvoiceNo() {
		return this.outdoorInvoiceNo;
	}

	public void setOutdoorInvoiceNo(String outdoorInvoiceNo) {
		this.outdoorInvoiceNo = outdoorInvoiceNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "GRN_NO", nullable = false, length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

	@Column(name = "DIRECTION_NO", nullable = false, length = 20)
	public String getDirectionNo() {
		return this.directionNo;
	}

	public void setDirectionNo(String directionNo) {
		this.directionNo = directionNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OutdoorIssueItemId))
			return false;
		OutdoorIssueItemId castOther = (OutdoorIssueItemId) other;

		return ((this.getOutdoorInvoiceNo() == castOther.getOutdoorInvoiceNo()) || (this
				.getOutdoorInvoiceNo() != null
				&& castOther.getOutdoorInvoiceNo() != null && this
				.getOutdoorInvoiceNo().equals(castOther.getOutdoorInvoiceNo())))
				&& ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
						.getPhUnitNo() != null
						&& castOther.getPhUnitNo() != null && this
						.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null && castOther.getItemNo() != null && this
						.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getGrnNo() == castOther.getGrnNo()) || (this
						.getGrnNo() != null && castOther.getGrnNo() != null && this
						.getGrnNo().equals(castOther.getGrnNo())))
				&& ((this.getDirectionNo() == castOther.getDirectionNo()) || (this
						.getDirectionNo() != null
						&& castOther.getDirectionNo() != null && this
						.getDirectionNo().equals(castOther.getDirectionNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getOutdoorInvoiceNo() == null ? 0 : this
						.getOutdoorInvoiceNo().hashCode());
		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getGrnNo() == null ? 0 : this.getGrnNo().hashCode());
		result = 37
				* result
				+ (getDirectionNo() == null ? 0 : this.getDirectionNo()
						.hashCode());
		return result;
	}

}
