package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OutdoorPatientIssue generated by hbm2java
 */
@Entity
@Table(name = "OUTDOOR_PATIENT_ISSUE")
public class OutdoorPatientIssue implements java.io.Serializable {

	private OutdoorPatientIssueId id;
	private PharmacyUnit pharmacyUnit;
	private String patientName;
	private String companyNo;
	private String doctorNo;
	private Date outdoorIssueDate;
	private Date outdoorDeliveryDate;
	private BigDecimal totalAmount;
	private BigDecimal discountAmount;
	private BigDecimal issuePaymentType;
	private BigDecimal printingStatus;
	private BigDecimal issueStatus;
	private BigDecimal cashierPrintStatus;
	private BigDecimal outdoorPatientType;
	private String userId;
	private String userIp;
	private BigDecimal creditStatus;
	private BigDecimal tokenNo;
	private BigDecimal totalWeight;
	private BigDecimal cashPayment;
	private BigDecimal cardPayment;
	private BigDecimal otherCharge;
	private String bankId;
	private String creditCardNumber;
	private BigDecimal injectionCharge;
	private Date cashierPrintDate;
	private String accId;
	private double points;
	private String custId;
	private BigDecimal bedCharge;
	private BigDecimal theatreCharge;
	private BigDecimal centralizedState;
	private String cardHolder;
	private Set<OutdoorIssueItem> outdoorIssueItems = new HashSet<OutdoorIssueItem>(
			0);

	public OutdoorPatientIssue() {
	}

	public OutdoorPatientIssue(OutdoorPatientIssueId id,
			PharmacyUnit pharmacyUnit, Date outdoorIssueDate,
			BigDecimal totalAmount, BigDecimal issuePaymentType,
			BigDecimal printingStatus, BigDecimal issueStatus,
			BigDecimal cashierPrintStatus, BigDecimal outdoorPatientType,
			String userId, String userIp, BigDecimal creditStatus,
			BigDecimal tokenNo, BigDecimal totalWeight, String accId,
			double points, String custId) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.outdoorIssueDate = outdoorIssueDate;
		this.totalAmount = totalAmount;
		this.issuePaymentType = issuePaymentType;
		this.printingStatus = printingStatus;
		this.issueStatus = issueStatus;
		this.cashierPrintStatus = cashierPrintStatus;
		this.outdoorPatientType = outdoorPatientType;
		this.userId = userId;
		this.userIp = userIp;
		this.creditStatus = creditStatus;
		this.tokenNo = tokenNo;
		this.totalWeight = totalWeight;
		this.accId = accId;
		this.points = points;
		this.custId = custId;
	}

	public OutdoorPatientIssue(OutdoorPatientIssueId id,
			PharmacyUnit pharmacyUnit, String patientName, String companyNo,
			String doctorNo, Date outdoorIssueDate, Date outdoorDeliveryDate,
			BigDecimal totalAmount, BigDecimal discountAmount,
			BigDecimal issuePaymentType, BigDecimal printingStatus,
			BigDecimal issueStatus, BigDecimal cashierPrintStatus,
			BigDecimal outdoorPatientType, String userId, String userIp,
			BigDecimal creditStatus, BigDecimal tokenNo,
			BigDecimal totalWeight, BigDecimal cashPayment,
			BigDecimal cardPayment, BigDecimal otherCharge, String bankId,
			String creditCardNumber, BigDecimal injectionCharge,
			Date cashierPrintDate, String accId, double points, String custId,
			BigDecimal bedCharge, BigDecimal theatreCharge,
			BigDecimal centralizedState, String cardHolder,
			Set<OutdoorIssueItem> outdoorIssueItems) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.patientName = patientName;
		this.companyNo = companyNo;
		this.doctorNo = doctorNo;
		this.outdoorIssueDate = outdoorIssueDate;
		this.outdoorDeliveryDate = outdoorDeliveryDate;
		this.totalAmount = totalAmount;
		this.discountAmount = discountAmount;
		this.issuePaymentType = issuePaymentType;
		this.printingStatus = printingStatus;
		this.issueStatus = issueStatus;
		this.cashierPrintStatus = cashierPrintStatus;
		this.outdoorPatientType = outdoorPatientType;
		this.userId = userId;
		this.userIp = userIp;
		this.creditStatus = creditStatus;
		this.tokenNo = tokenNo;
		this.totalWeight = totalWeight;
		this.cashPayment = cashPayment;
		this.cardPayment = cardPayment;
		this.otherCharge = otherCharge;
		this.bankId = bankId;
		this.creditCardNumber = creditCardNumber;
		this.injectionCharge = injectionCharge;
		this.cashierPrintDate = cashierPrintDate;
		this.accId = accId;
		this.points = points;
		this.custId = custId;
		this.bedCharge = bedCharge;
		this.theatreCharge = theatreCharge;
		this.centralizedState = centralizedState;
		this.cardHolder = cardHolder;
		this.outdoorIssueItems = outdoorIssueItems;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "outdoorInvoiceNo", column = @Column(name = "OUTDOOR_INVOICE_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)) })
	public OutdoorPatientIssueId getId() {
		return this.id;
	}

	public void setId(OutdoorPatientIssueId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Column(name = "PATIENT_NAME", length = 100)
	public String getPatientName() {
		return this.patientName;
	}

	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}

	@Column(name = "COMPANY_NO", length = 100)
	public String getCompanyNo() {
		return this.companyNo;
	}

	public void setCompanyNo(String companyNo) {
		this.companyNo = companyNo;
	}

	@Column(name = "DOCTOR_NO", length = 50)
	public String getDoctorNo() {
		return this.doctorNo;
	}

	public void setDoctorNo(String doctorNo) {
		this.doctorNo = doctorNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OUTDOOR_ISSUE_DATE", nullable = false, length = 7)
	public Date getOutdoorIssueDate() {
		return this.outdoorIssueDate;
	}

	public void setOutdoorIssueDate(Date outdoorIssueDate) {
		this.outdoorIssueDate = outdoorIssueDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OUTDOOR_DELIVERY_DATE", length = 7)
	public Date getOutdoorDeliveryDate() {
		return this.outdoorDeliveryDate;
	}

	public void setOutdoorDeliveryDate(Date outdoorDeliveryDate) {
		this.outdoorDeliveryDate = outdoorDeliveryDate;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "DISCOUNT_AMOUNT", precision = 10)
	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	@Column(name = "ISSUE_PAYMENT_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getIssuePaymentType() {
		return this.issuePaymentType;
	}

	public void setIssuePaymentType(BigDecimal issuePaymentType) {
		this.issuePaymentType = issuePaymentType;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "ISSUE_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getIssueStatus() {
		return this.issueStatus;
	}

	public void setIssueStatus(BigDecimal issueStatus) {
		this.issueStatus = issueStatus;
	}

	@Column(name = "CASHIER_PRINT_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getCashierPrintStatus() {
		return this.cashierPrintStatus;
	}

	public void setCashierPrintStatus(BigDecimal cashierPrintStatus) {
		this.cashierPrintStatus = cashierPrintStatus;
	}

	@Column(name = "OUTDOOR_PATIENT_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getOutdoorPatientType() {
		return this.outdoorPatientType;
	}

	public void setOutdoorPatientType(BigDecimal outdoorPatientType) {
		this.outdoorPatientType = outdoorPatientType;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "CREDIT_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getCreditStatus() {
		return this.creditStatus;
	}

	public void setCreditStatus(BigDecimal creditStatus) {
		this.creditStatus = creditStatus;
	}

	@Column(name = "TOKEN_NO", nullable = false, precision = 38, scale = 0)
	public BigDecimal getTokenNo() {
		return this.tokenNo;
	}

	public void setTokenNo(BigDecimal tokenNo) {
		this.tokenNo = tokenNo;
	}

	@Column(name = "TOTAL_WEIGHT", nullable = false, precision = 10)
	public BigDecimal getTotalWeight() {
		return this.totalWeight;
	}

	public void setTotalWeight(BigDecimal totalWeight) {
		this.totalWeight = totalWeight;
	}

	@Column(name = "CASH_PAYMENT", precision = 38)
	public BigDecimal getCashPayment() {
		return this.cashPayment;
	}

	public void setCashPayment(BigDecimal cashPayment) {
		this.cashPayment = cashPayment;
	}

	@Column(name = "CARD_PAYMENT", precision = 38)
	public BigDecimal getCardPayment() {
		return this.cardPayment;
	}

	public void setCardPayment(BigDecimal cardPayment) {
		this.cardPayment = cardPayment;
	}

	@Column(name = "OTHER_CHARGE", precision = 38)
	public BigDecimal getOtherCharge() {
		return this.otherCharge;
	}

	public void setOtherCharge(BigDecimal otherCharge) {
		this.otherCharge = otherCharge;
	}

	@Column(name = "BANK_ID", length = 25)
	public String getBankId() {
		return this.bankId;
	}

	public void setBankId(String bankId) {
		this.bankId = bankId;
	}

	@Column(name = "CREDIT_CARD_NUMBER", length = 20)
	public String getCreditCardNumber() {
		return this.creditCardNumber;
	}

	public void setCreditCardNumber(String creditCardNumber) {
		this.creditCardNumber = creditCardNumber;
	}

	@Column(name = "INJECTION_CHARGE", precision = 38)
	public BigDecimal getInjectionCharge() {
		return this.injectionCharge;
	}

	public void setInjectionCharge(BigDecimal injectionCharge) {
		this.injectionCharge = injectionCharge;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CASHIER_PRINT_DATE", length = 7)
	public Date getCashierPrintDate() {
		return this.cashierPrintDate;
	}

	public void setCashierPrintDate(Date cashierPrintDate) {
		this.cashierPrintDate = cashierPrintDate;
	}

	@Column(name = "ACC_ID", nullable = false, length = 10)
	public String getAccId() {
		return this.accId;
	}

	public void setAccId(String accId) {
		this.accId = accId;
	}

	@Column(name = "POINTS", nullable = false, precision = 126, scale = 0)
	public double getPoints() {
		return this.points;
	}

	public void setPoints(double points) {
		this.points = points;
	}

	@Column(name = "CUST_ID", nullable = false, length = 10)
	public String getCustId() {
		return this.custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	@Column(name = "BED_CHARGE", precision = 38, scale = 0)
	public BigDecimal getBedCharge() {
		return this.bedCharge;
	}

	public void setBedCharge(BigDecimal bedCharge) {
		this.bedCharge = bedCharge;
	}

	@Column(name = "THEATRE_CHARGE", precision = 38, scale = 0)
	public BigDecimal getTheatreCharge() {
		return this.theatreCharge;
	}

	public void setTheatreCharge(BigDecimal theatreCharge) {
		this.theatreCharge = theatreCharge;
	}

	@Column(name = "CENTRALIZED_STATE", precision = 38)
	public BigDecimal getCentralizedState() {
		return this.centralizedState;
	}

	public void setCentralizedState(BigDecimal centralizedState) {
		this.centralizedState = centralizedState;
	}

	@Column(name = "CARD_HOLDER", length = 100)
	public String getCardHolder() {
		return this.cardHolder;
	}

	public void setCardHolder(String cardHolder) {
		this.cardHolder = cardHolder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "outdoorPatientIssue")
	public Set<OutdoorIssueItem> getOutdoorIssueItems() {
		return this.outdoorIssueItems;
	}

	public void setOutdoorIssueItems(Set<OutdoorIssueItem> outdoorIssueItems) {
		this.outdoorIssueItems = outdoorIssueItems;
	}

}
