package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OutdoorIssueItem generated by hbm2java
 */
@Entity
@Table(name = "OUTDOOR_ISSUE_ITEM")
public class OutdoorIssueItem implements java.io.Serializable {

	private OutdoorIssueItemId id;
	private Directions directions;
	private OutdoorPatientIssue outdoorPatientIssue;
	private double quantity;
	private BigDecimal totalAmount;
	private BigDecimal totalWeight;
	private BigDecimal discountRate;
	private BigDecimal netAmount;

	public OutdoorIssueItem() {
	}

	public OutdoorIssueItem(OutdoorIssueItemId id, Directions directions,
			OutdoorPatientIssue outdoorPatientIssue, double quantity,
			BigDecimal totalAmount, BigDecimal totalWeight, BigDecimal netAmount) {
		this.id = id;
		this.directions = directions;
		this.outdoorPatientIssue = outdoorPatientIssue;
		this.quantity = quantity;
		this.totalAmount = totalAmount;
		this.totalWeight = totalWeight;
		this.netAmount = netAmount;
	}

	public OutdoorIssueItem(OutdoorIssueItemId id, Directions directions,
			OutdoorPatientIssue outdoorPatientIssue, double quantity,
			BigDecimal totalAmount, BigDecimal totalWeight,
			BigDecimal discountRate, BigDecimal netAmount) {
		this.id = id;
		this.directions = directions;
		this.outdoorPatientIssue = outdoorPatientIssue;
		this.quantity = quantity;
		this.totalAmount = totalAmount;
		this.totalWeight = totalWeight;
		this.discountRate = discountRate;
		this.netAmount = netAmount;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "outdoorInvoiceNo", column = @Column(name = "OUTDOOR_INVOICE_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "directionNo", column = @Column(name = "DIRECTION_NO", nullable = false, length = 20)) })
	public OutdoorIssueItemId getId() {
		return this.id;
	}

	public void setId(OutdoorIssueItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DIRECTION_NO", nullable = false, insertable = false, updatable = false)
	public Directions getDirections() {
		return this.directions;
	}

	public void setDirections(Directions directions) {
		this.directions = directions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "OUTDOOR_INVOICE_NO", referencedColumnName = "OUTDOOR_INVOICE_NO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PH_UNIT_NO", referencedColumnName = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false) })
	public OutdoorPatientIssue getOutdoorPatientIssue() {
		return this.outdoorPatientIssue;
	}

	public void setOutdoorPatientIssue(OutdoorPatientIssue outdoorPatientIssue) {
		this.outdoorPatientIssue = outdoorPatientIssue;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "TOTAL_WEIGHT", nullable = false, precision = 10)
	public BigDecimal getTotalWeight() {
		return this.totalWeight;
	}

	public void setTotalWeight(BigDecimal totalWeight) {
		this.totalWeight = totalWeight;
	}

	@Column(name = "DISCOUNT_RATE", precision = 10)
	public BigDecimal getDiscountRate() {
		return this.discountRate;
	}

	public void setDiscountRate(BigDecimal discountRate) {
		this.discountRate = discountRate;
	}

	@Column(name = "NET_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(BigDecimal netAmount) {
		this.netAmount = netAmount;
	}

}
