package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PatientIssueReturnItem generated by hbm2java
 */
@Entity
@Table(name = "PATIENT_ISSUE_RETURN_ITEM")
public class PatientIssueReturnItem implements java.io.Serializable {

	private PatientIssueReturnItemId id;
	private PatientIssueReturn patientIssueReturn;
	private DrugItem drugItem;
	private double quantity;
	private BigDecimal totalAmount;

	public PatientIssueReturnItem() {
	}

	public PatientIssueReturnItem(PatientIssueReturnItemId id,
			PatientIssueReturn patientIssueReturn, DrugItem drugItem,
			double quantity, BigDecimal totalAmount) {
		this.id = id;
		this.patientIssueReturn = patientIssueReturn;
		this.drugItem = drugItem;
		this.quantity = quantity;
		this.totalAmount = totalAmount;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "patientIssueReturnNo", column = @Column(name = "PATIENT_ISSUE_RETURN_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)) })
	public PatientIssueReturnItemId getId() {
		return this.id;
	}

	public void setId(PatientIssueReturnItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "PH_UNIT_NO", referencedColumnName = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "PATIENT_ISSUE_RETURN_NO", referencedColumnName = "PATIENT_ISSUE_RETURN_NO", nullable = false, insertable = false, updatable = false) })
	public PatientIssueReturn getPatientIssueReturn() {
		return this.patientIssueReturn;
	}

	public void setPatientIssueReturn(PatientIssueReturn patientIssueReturn) {
		this.patientIssueReturn = patientIssueReturn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_NO", nullable = false, insertable = false, updatable = false)
	public DrugItem getDrugItem() {
		return this.drugItem;
	}

	public void setDrugItem(DrugItem drugItem) {
		this.drugItem = drugItem;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "TOTAL_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

}
