package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientIssueCancel generated by hbm2java
 */
@Entity
@Table(name = "PATIENT_ISSUE_CANCEL")
public class PatientIssueCancel implements java.io.Serializable {

	private PatientIssueCancelId id;
	private Date patientIssueCancelDate;
	private BigDecimal printingStatus;
	private BigDecimal patientIssueCancelType;
	private String userId;
	private String userIp;

	public PatientIssueCancel() {
	}

	public PatientIssueCancel(PatientIssueCancelId id,
			Date patientIssueCancelDate, BigDecimal printingStatus,
			BigDecimal patientIssueCancelType, String userId, String userIp) {
		this.id = id;
		this.patientIssueCancelDate = patientIssueCancelDate;
		this.printingStatus = printingStatus;
		this.patientIssueCancelType = patientIssueCancelType;
		this.userId = userId;
		this.userIp = userIp;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT__NO", nullable = false, length = 20)),
			@AttributeOverride(name = "patientIssueCancelNo", column = @Column(name = "PATIENT_ISSUE_CANCEL_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "issueNo", column = @Column(name = "ISSUE_NO", nullable = false, length = 20)) })
	public PatientIssueCancelId getId() {
		return this.id;
	}

	public void setId(PatientIssueCancelId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PATIENT_ISSUE_CANCEL_DATE", nullable = false, length = 7)
	public Date getPatientIssueCancelDate() {
		return this.patientIssueCancelDate;
	}

	public void setPatientIssueCancelDate(Date patientIssueCancelDate) {
		this.patientIssueCancelDate = patientIssueCancelDate;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "PATIENT_ISSUE_CANCEL_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPatientIssueCancelType() {
		return this.patientIssueCancelType;
	}

	public void setPatientIssueCancelType(BigDecimal patientIssueCancelType) {
		this.patientIssueCancelType = patientIssueCancelType;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

}
