package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PaymentTypeId generated by hbm2java
 */
@Embeddable
public class PaymentTypeId implements java.io.Serializable {

	private String phUnitNo;
	private String paymentId;

	public PaymentTypeId() {
	}

	public PaymentTypeId(String phUnitNo, String paymentId) {
		this.phUnitNo = phUnitNo;
		this.paymentId = paymentId;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "PAYMENT_ID", nullable = false, length = 20)
	public String getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(String paymentId) {
		this.paymentId = paymentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PaymentTypeId))
			return false;
		PaymentTypeId castOther = (PaymentTypeId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getPaymentId() == castOther.getPaymentId()) || (this
						.getPaymentId() != null
						&& castOther.getPaymentId() != null && this
						.getPaymentId().equals(castOther.getPaymentId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37 * result
				+ (getPaymentId() == null ? 0 : this.getPaymentId().hashCode());
		return result;
	}

}
