package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PaymentType generated by hbm2java
 */
@Entity
@Table(name = "PAYMENT_TYPE")
public class PaymentType implements java.io.Serializable {

	private PaymentTypeId id;
	private PharmacyUnit pharmacyUnit;
	private String paymentDesc;
	private String maxValue;

	public PaymentType() {
	}

	public PaymentType(PaymentTypeId id, PharmacyUnit pharmacyUnit) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
	}

	public PaymentType(PaymentTypeId id, PharmacyUnit pharmacyUnit,
			String paymentDesc, String maxValue) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.paymentDesc = paymentDesc;
		this.maxValue = maxValue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "paymentId", column = @Column(name = "PAYMENT_ID", nullable = false, length = 20)) })
	public PaymentTypeId getId() {
		return this.id;
	}

	public void setId(PaymentTypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PAYMENT_ID", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Column(name = "PAYMENT_DESC", length = 20)
	public String getPaymentDesc() {
		return this.paymentDesc;
	}

	public void setPaymentDesc(String paymentDesc) {
		this.paymentDesc = paymentDesc;
	}

	@Column(name = "MAX_VALUE", length = 20)
	public String getMaxValue() {
		return this.maxValue;
	}

	public void setMaxValue(String maxValue) {
		this.maxValue = maxValue;
	}

}
