package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PhaCustomers generated by hbm2java
 */
@Entity
@Table(name = "PHA_CUSTOMERS")
public class PhaCustomers implements java.io.Serializable {

	private PhaCustomersId id;
	private String barCode;
	private String nic;
	private String firstName;
	private String lastName;
	private String title;
	private String address1;
	private String address2;
	private String address3;
	private String telphone;
	private String mobile;
	private BigDecimal sex;
	private String userId;
	private String userIp;
	private Date regDate;
	private BigDecimal status;
	private String email;
	private String cardNo;
	private Double points;

	public PhaCustomers() {
	}

	public PhaCustomers(PhaCustomersId id, String barCode, String nic,
			String firstName, String lastName, String userId, String userIp,
			Date regDate, BigDecimal status) {
		this.id = id;
		this.barCode = barCode;
		this.nic = nic;
		this.firstName = firstName;
		this.lastName = lastName;
		this.userId = userId;
		this.userIp = userIp;
		this.regDate = regDate;
		this.status = status;
	}

	public PhaCustomers(PhaCustomersId id, String barCode, String nic,
			String firstName, String lastName, String title, String address1,
			String address2, String address3, String telphone, String mobile,
			BigDecimal sex, String userId, String userIp, Date regDate,
			BigDecimal status, String email, String cardNo, Double points) {
		this.id = id;
		this.barCode = barCode;
		this.nic = nic;
		this.firstName = firstName;
		this.lastName = lastName;
		this.title = title;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.telphone = telphone;
		this.mobile = mobile;
		this.sex = sex;
		this.userId = userId;
		this.userIp = userIp;
		this.regDate = regDate;
		this.status = status;
		this.email = email;
		this.cardNo = cardNo;
		this.points = points;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "custNo", column = @Column(name = "CUST_NO", nullable = false, length = 10)) })
	public PhaCustomersId getId() {
		return this.id;
	}

	public void setId(PhaCustomersId id) {
		this.id = id;
	}

	@Column(name = "BAR_CODE", nullable = false, length = 50)
	public String getBarCode() {
		return this.barCode;
	}

	public void setBarCode(String barCode) {
		this.barCode = barCode;
	}

	@Column(name = "NIC", nullable = false, length = 10)
	public String getNic() {
		return this.nic;
	}

	public void setNic(String nic) {
		this.nic = nic;
	}

	@Column(name = "FIRST_NAME", nullable = false, length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "TITLE", length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "ADDRESS1", length = 50)
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "ADDRESS2", length = 100)
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "ADDRESS3", length = 100)
	public String getAddress3() {
		return this.address3;
	}

	public void setAddress3(String address3) {
		this.address3 = address3;
	}

	@Column(name = "TELPHONE", length = 10)
	public String getTelphone() {
		return this.telphone;
	}

	public void setTelphone(String telphone) {
		this.telphone = telphone;
	}

	@Column(name = "MOBILE", length = 10)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "SEX", precision = 22, scale = 0)
	public BigDecimal getSex() {
		return this.sex;
	}

	public void setSex(BigDecimal sex) {
		this.sex = sex;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REG_DATE", nullable = false, length = 7)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	@Column(name = "STATUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "CARD_NO", length = 10)
	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	@Column(name = "POINTS", precision = 126, scale = 0)
	public Double getPoints() {
		return this.points;
	}

	public void setPoints(Double points) {
		this.points = points;
	}

}
