package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PhaParameters generated by hbm2java
 */
@Entity
@Table(name = "PHA_PARAMETERS")
public class PhaParameters implements java.io.Serializable {

	private PhaParametersId id;
	private String prefixValue;
	private BigDecimal nextValue;

	public PhaParameters() {
	}

	public PhaParameters(PhaParametersId id, String prefixValue,
			BigDecimal nextValue) {
		this.id = id;
		this.prefixValue = prefixValue;
		this.nextValue = nextValue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "parameterNo", column = @Column(name = "PARAMETER_NO", nullable = false, precision = 38, scale = 0)),
			@AttributeOverride(name = "parameterName", column = @Column(name = "PARAMETER_NAME", nullable = false, length = 50)) })
	public PhaParametersId getId() {
		return this.id;
	}

	public void setId(PhaParametersId id) {
		this.id = id;
	}

	@Column(name = "PREFIX_VALUE", nullable = false, length = 20)
	public String getPrefixValue() {
		return this.prefixValue;
	}

	public void setPrefixValue(String prefixValue) {
		this.prefixValue = prefixValue;
	}

	@Column(name = "NEXT_VALUE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getNextValue() {
		return this.nextValue;
	}

	public void setNextValue(BigDecimal nextValue) {
		this.nextValue = nextValue;
	}

}
