package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhaParametersId generated by hbm2java
 */
@Embeddable
public class PhaParametersId implements java.io.Serializable {

	private String phUnitNo;
	private BigDecimal parameterNo;
	private String parameterName;

	public PhaParametersId() {
	}

	public PhaParametersId(String phUnitNo, BigDecimal parameterNo,
			String parameterName) {
		this.phUnitNo = phUnitNo;
		this.parameterNo = parameterNo;
		this.parameterName = parameterName;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "PARAMETER_NO", nullable = false, precision = 38, scale = 0)
	public BigDecimal getParameterNo() {
		return this.parameterNo;
	}

	public void setParameterNo(BigDecimal parameterNo) {
		this.parameterNo = parameterNo;
	}

	@Column(name = "PARAMETER_NAME", nullable = false, length = 50)
	public String getParameterName() {
		return this.parameterName;
	}

	public void setParameterName(String parameterName) {
		this.parameterName = parameterName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhaParametersId))
			return false;
		PhaParametersId castOther = (PhaParametersId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getParameterNo() == castOther.getParameterNo()) || (this
						.getParameterNo() != null
						&& castOther.getParameterNo() != null && this
						.getParameterNo().equals(castOther.getParameterNo())))
				&& ((this.getParameterName() == castOther.getParameterName()) || (this
						.getParameterName() != null
						&& castOther.getParameterName() != null && this
						.getParameterName()
						.equals(castOther.getParameterName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37
				* result
				+ (getParameterNo() == null ? 0 : this.getParameterNo()
						.hashCode());
		result = 37
				* result
				+ (getParameterName() == null ? 0 : this.getParameterName()
						.hashCode());
		return result;
	}

}
