package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PharmacyIssueCancel generated by hbm2java
 */
@Entity
@Table(name = "PHARMACY_ISSUE_CANCEL")
public class PharmacyIssueCancel implements java.io.Serializable {

	private PharmacyIssueCancelId id;
	private String issueNo;
	private Date pharmacyIssueCancelDate;
	private BigDecimal printingStatus;
	private String userId;
	private String userIp;

	public PharmacyIssueCancel() {
	}

	public PharmacyIssueCancel(PharmacyIssueCancelId id, String issueNo,
			Date pharmacyIssueCancelDate, BigDecimal printingStatus,
			String userId, String userIp) {
		this.id = id;
		this.issueNo = issueNo;
		this.pharmacyIssueCancelDate = pharmacyIssueCancelDate;
		this.printingStatus = printingStatus;
		this.userId = userId;
		this.userIp = userIp;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "pharmacyIssueCancelNo", column = @Column(name = "PHARMACY_ISSUE_CANCEL_NO", nullable = false, length = 20)) })
	public PharmacyIssueCancelId getId() {
		return this.id;
	}

	public void setId(PharmacyIssueCancelId id) {
		this.id = id;
	}

	@Column(name = "ISSUE_NO", nullable = false, length = 20)
	public String getIssueNo() {
		return this.issueNo;
	}

	public void setIssueNo(String issueNo) {
		this.issueNo = issueNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PHARMACY_ISSUE_CANCEL_DATE", nullable = false, length = 7)
	public Date getPharmacyIssueCancelDate() {
		return this.pharmacyIssueCancelDate;
	}

	public void setPharmacyIssueCancelDate(Date pharmacyIssueCancelDate) {
		this.pharmacyIssueCancelDate = pharmacyIssueCancelDate;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

}
