package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PharmacyOrderDrugItemId generated by hbm2java
 */
@Embeddable
public class PharmacyOrderDrugItemId implements java.io.Serializable {

	private String orderNo;
	private String itemNo;

	public PharmacyOrderDrugItemId() {
	}

	public PharmacyOrderDrugItemId(String orderNo, String itemNo) {
		this.orderNo = orderNo;
		this.itemNo = itemNo;
	}

	@Column(name = "ORDER_NO", nullable = false, length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmacyOrderDrugItemId))
			return false;
		PharmacyOrderDrugItemId castOther = (PharmacyOrderDrugItemId) other;

		return ((this.getOrderNo() == castOther.getOrderNo()) || (this
				.getOrderNo() != null && castOther.getOrderNo() != null && this
				.getOrderNo().equals(castOther.getOrderNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null && castOther.getItemNo() != null && this
						.getItemNo().equals(castOther.getItemNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrderNo() == null ? 0 : this.getOrderNo().hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		return result;
	}

}
