package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PharmacyIssueCancelItemId generated by hbm2java
 */
@Embeddable
public class PharmacyIssueCancelItemId implements java.io.Serializable {

	private String phUnitNo;
	private String pharmacyIssueCancelNo;
	private String itemNo;
	private String grnNo;

	public PharmacyIssueCancelItemId() {
	}

	public PharmacyIssueCancelItemId(String phUnitNo,
			String pharmacyIssueCancelNo, String itemNo, String grnNo) {
		this.phUnitNo = phUnitNo;
		this.pharmacyIssueCancelNo = pharmacyIssueCancelNo;
		this.itemNo = itemNo;
		this.grnNo = grnNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "PHARMACY_ISSUE_CANCEL_NO", nullable = false, length = 20)
	public String getPharmacyIssueCancelNo() {
		return this.pharmacyIssueCancelNo;
	}

	public void setPharmacyIssueCancelNo(String pharmacyIssueCancelNo) {
		this.pharmacyIssueCancelNo = pharmacyIssueCancelNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "GRN_NO", nullable = false, length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmacyIssueCancelItemId))
			return false;
		PharmacyIssueCancelItemId castOther = (PharmacyIssueCancelItemId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getPharmacyIssueCancelNo() == castOther
						.getPharmacyIssueCancelNo()) || (this
						.getPharmacyIssueCancelNo() != null
						&& castOther.getPharmacyIssueCancelNo() != null && this
						.getPharmacyIssueCancelNo().equals(
								castOther.getPharmacyIssueCancelNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null && castOther.getItemNo() != null && this
						.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getGrnNo() == castOther.getGrnNo()) || (this
						.getGrnNo() != null && castOther.getGrnNo() != null && this
						.getGrnNo().equals(castOther.getGrnNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37
				* result
				+ (getPharmacyIssueCancelNo() == null ? 0 : this
						.getPharmacyIssueCancelNo().hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getGrnNo() == null ? 0 : this.getGrnNo().hashCode());
		return result;
	}

}
