package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PharmacyUnitLogId generated by hbm2java
 */
@Embeddable
public class PharmacyUnitLogId implements java.io.Serializable {

	private String phUnitNo;
	private BigDecimal pharmacyUnitLogNo;

	public PharmacyUnitLogId() {
	}

	public PharmacyUnitLogId(String phUnitNo, BigDecimal pharmacyUnitLogNo) {
		this.phUnitNo = phUnitNo;
		this.pharmacyUnitLogNo = pharmacyUnitLogNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "PHARMACY_UNIT_LOG_NO", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPharmacyUnitLogNo() {
		return this.pharmacyUnitLogNo;
	}

	public void setPharmacyUnitLogNo(BigDecimal pharmacyUnitLogNo) {
		this.pharmacyUnitLogNo = pharmacyUnitLogNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmacyUnitLogId))
			return false;
		PharmacyUnitLogId castOther = (PharmacyUnitLogId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getPharmacyUnitLogNo() == castOther
						.getPharmacyUnitLogNo()) || (this
						.getPharmacyUnitLogNo() != null
						&& castOther.getPharmacyUnitLogNo() != null && this
						.getPharmacyUnitLogNo().equals(
								castOther.getPharmacyUnitLogNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37
				* result
				+ (getPharmacyUnitLogNo() == null ? 0 : this
						.getPharmacyUnitLogNo().hashCode());
		return result;
	}

}
