package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PharmacyIssueCancelId generated by hbm2java
 */
@Embeddable
public class PharmacyIssueCancelId implements java.io.Serializable {

	private String phUnitNo;
	private String pharmacyIssueCancelNo;

	public PharmacyIssueCancelId() {
	}

	public PharmacyIssueCancelId(String phUnitNo, String pharmacyIssueCancelNo) {
		this.phUnitNo = phUnitNo;
		this.pharmacyIssueCancelNo = pharmacyIssueCancelNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "PHARMACY_ISSUE_CANCEL_NO", nullable = false, length = 20)
	public String getPharmacyIssueCancelNo() {
		return this.pharmacyIssueCancelNo;
	}

	public void setPharmacyIssueCancelNo(String pharmacyIssueCancelNo) {
		this.pharmacyIssueCancelNo = pharmacyIssueCancelNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PharmacyIssueCancelId))
			return false;
		PharmacyIssueCancelId castOther = (PharmacyIssueCancelId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getPharmacyIssueCancelNo() == castOther
						.getPharmacyIssueCancelNo()) || (this
						.getPharmacyIssueCancelNo() != null
						&& castOther.getPharmacyIssueCancelNo() != null && this
						.getPharmacyIssueCancelNo().equals(
								castOther.getPharmacyIssueCancelNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37
				* result
				+ (getPharmacyIssueCancelNo() == null ? 0 : this
						.getPharmacyIssueCancelNo().hashCode());
		return result;
	}

}
