package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PharmacyOrderDrugItem generated by hbm2java
 */
@Entity
@Table(name = "PHARMACY_ORDER_DRUG_ITEM")
public class PharmacyOrderDrugItem implements java.io.Serializable {

	private PharmacyOrderDrugItemId id;
	private double quantity;
	private double quantityInHand;

	public PharmacyOrderDrugItem() {
	}

	public PharmacyOrderDrugItem(PharmacyOrderDrugItemId id, double quantity,
			double quantityInHand) {
		this.id = id;
		this.quantity = quantity;
		this.quantityInHand = quantityInHand;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "orderNo", column = @Column(name = "ORDER_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)) })
	public PharmacyOrderDrugItemId getId() {
		return this.id;
	}

	public void setId(PharmacyOrderDrugItemId id) {
		this.id = id;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "QUANTITY_IN_HAND", nullable = false, precision = 126, scale = 0)
	public double getQuantityInHand() {
		return this.quantityInHand;
	}

	public void setQuantityInHand(double quantityInHand) {
		this.quantityInHand = quantityInHand;
	}

}
