package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PharmacyOrder generated by hbm2java
 */
@Entity
@Table(name = "PHARMACY_ORDER")
public class PharmacyOrder implements java.io.Serializable {

	private String orderNo;
	private PharmacyUnit pharmacyUnitByFromUnitNo;
	private PharmacyUnit pharmacyUnitByToUnitNo;
	private BigDecimal orderType;
	private BigDecimal orderImportance;
	private Date orderDate;
	private String userId;
	private String userIp;
	private BigDecimal printingStatus;
	private BigDecimal orderStatus;

	public PharmacyOrder() {
	}

	public PharmacyOrder(String orderNo, PharmacyUnit pharmacyUnitByFromUnitNo,
			PharmacyUnit pharmacyUnitByToUnitNo, BigDecimal orderType,
			BigDecimal orderImportance, Date orderDate, String userId,
			String userIp, BigDecimal printingStatus) {
		this.orderNo = orderNo;
		this.pharmacyUnitByFromUnitNo = pharmacyUnitByFromUnitNo;
		this.pharmacyUnitByToUnitNo = pharmacyUnitByToUnitNo;
		this.orderType = orderType;
		this.orderImportance = orderImportance;
		this.orderDate = orderDate;
		this.userId = userId;
		this.userIp = userIp;
		this.printingStatus = printingStatus;
	}

	public PharmacyOrder(String orderNo, PharmacyUnit pharmacyUnitByFromUnitNo,
			PharmacyUnit pharmacyUnitByToUnitNo, BigDecimal orderType,
			BigDecimal orderImportance, Date orderDate, String userId,
			String userIp, BigDecimal printingStatus, BigDecimal orderStatus) {
		this.orderNo = orderNo;
		this.pharmacyUnitByFromUnitNo = pharmacyUnitByFromUnitNo;
		this.pharmacyUnitByToUnitNo = pharmacyUnitByToUnitNo;
		this.orderType = orderType;
		this.orderImportance = orderImportance;
		this.orderDate = orderDate;
		this.userId = userId;
		this.userIp = userIp;
		this.printingStatus = printingStatus;
		this.orderStatus = orderStatus;
	}

	@Id
	@Column(name = "ORDER_NO", unique = true, nullable = false, length = 20)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FROM_UNIT_NO", nullable = false)
	public PharmacyUnit getPharmacyUnitByFromUnitNo() {
		return this.pharmacyUnitByFromUnitNo;
	}

	public void setPharmacyUnitByFromUnitNo(
			PharmacyUnit pharmacyUnitByFromUnitNo) {
		this.pharmacyUnitByFromUnitNo = pharmacyUnitByFromUnitNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TO_UNIT_NO", nullable = false)
	public PharmacyUnit getPharmacyUnitByToUnitNo() {
		return this.pharmacyUnitByToUnitNo;
	}

	public void setPharmacyUnitByToUnitNo(PharmacyUnit pharmacyUnitByToUnitNo) {
		this.pharmacyUnitByToUnitNo = pharmacyUnitByToUnitNo;
	}

	@Column(name = "ORDER_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getOrderType() {
		return this.orderType;
	}

	public void setOrderType(BigDecimal orderType) {
		this.orderType = orderType;
	}

	@Column(name = "ORDER_IMPORTANCE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getOrderImportance() {
		return this.orderImportance;
	}

	public void setOrderImportance(BigDecimal orderImportance) {
		this.orderImportance = orderImportance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ORDER_DATE", nullable = false, length = 7)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "ORDER_STATUS", precision = 38, scale = 0)
	public BigDecimal getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(BigDecimal orderStatus) {
		this.orderStatus = orderStatus;
	}

}
