package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PharmacyValuation generated by hbm2java
 */
@Entity
@Table(name = "PHARMACY_VALUATION")
public class PharmacyValuation implements java.io.Serializable {

	private BigDecimal recordCode;
	private String unitNo;
	private String category;
	private BigDecimal costTotal;
	private BigDecimal retailTotal;
	private Date valueDate;

	public PharmacyValuation() {
	}

	public PharmacyValuation(BigDecimal recordCode, String unitNo,
			String category, BigDecimal costTotal, BigDecimal retailTotal,
			Date valueDate) {
		this.recordCode = recordCode;
		this.unitNo = unitNo;
		this.category = category;
		this.costTotal = costTotal;
		this.retailTotal = retailTotal;
		this.valueDate = valueDate;
	}

	@Id
	@Column(name = "RECORD_CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRecordCode() {
		return this.recordCode;
	}

	public void setRecordCode(BigDecimal recordCode) {
		this.recordCode = recordCode;
	}

	@Column(name = "UNIT_NO", nullable = false, length = 20)
	public String getUnitNo() {
		return this.unitNo;
	}

	public void setUnitNo(String unitNo) {
		this.unitNo = unitNo;
	}

	@Column(name = "CATEGORY", nullable = false, length = 20)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "COST_TOTAL", nullable = false, precision = 20)
	public BigDecimal getCostTotal() {
		return this.costTotal;
	}

	public void setCostTotal(BigDecimal costTotal) {
		this.costTotal = costTotal;
	}

	@Column(name = "RETAIL_TOTAL", nullable = false, precision = 20)
	public BigDecimal getRetailTotal() {
		return this.retailTotal;
	}

	public void setRetailTotal(BigDecimal retailTotal) {
		this.retailTotal = retailTotal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALUE_DATE", nullable = false, length = 7)
	public Date getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

}
