package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PharmacyUnitLog generated by hbm2java
 */
@Entity
@Table(name = "PHARMACY_UNIT_LOG")
public class PharmacyUnitLog implements java.io.Serializable {

	private PharmacyUnitLogId id;
	private PharmacyUnit pharmacyUnit;
	private String identityCode;
	private String lastValue;
	private Date pharmacyUnitLogDate;
	private String userId;
	private String userIp;
	private String identityCode1;
	private String logDescription;
	private String related;

	public PharmacyUnitLog() {
	}

	public PharmacyUnitLog(PharmacyUnitLogId id, PharmacyUnit pharmacyUnit,
			String identityCode, String lastValue, Date pharmacyUnitLogDate,
			String userId, String userIp, String related) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.identityCode = identityCode;
		this.lastValue = lastValue;
		this.pharmacyUnitLogDate = pharmacyUnitLogDate;
		this.userId = userId;
		this.userIp = userIp;
		this.related = related;
	}

	public PharmacyUnitLog(PharmacyUnitLogId id, PharmacyUnit pharmacyUnit,
			String identityCode, String lastValue, Date pharmacyUnitLogDate,
			String userId, String userIp, String identityCode1,
			String logDescription, String related) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.identityCode = identityCode;
		this.lastValue = lastValue;
		this.pharmacyUnitLogDate = pharmacyUnitLogDate;
		this.userId = userId;
		this.userIp = userIp;
		this.identityCode1 = identityCode1;
		this.logDescription = logDescription;
		this.related = related;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "pharmacyUnitLogNo", column = @Column(name = "PHARMACY_UNIT_LOG_NO", nullable = false, precision = 38, scale = 0)) })
	public PharmacyUnitLogId getId() {
		return this.id;
	}

	public void setId(PharmacyUnitLogId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Column(name = "IDENTITY_CODE", nullable = false, length = 200)
	public String getIdentityCode() {
		return this.identityCode;
	}

	public void setIdentityCode(String identityCode) {
		this.identityCode = identityCode;
	}

	@Column(name = "LAST_VALUE", nullable = false, length = 200)
	public String getLastValue() {
		return this.lastValue;
	}

	public void setLastValue(String lastValue) {
		this.lastValue = lastValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PHARMACY_UNIT_LOG_DATE", nullable = false, length = 7)
	public Date getPharmacyUnitLogDate() {
		return this.pharmacyUnitLogDate;
	}

	public void setPharmacyUnitLogDate(Date pharmacyUnitLogDate) {
		this.pharmacyUnitLogDate = pharmacyUnitLogDate;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "IDENTITY_CODE1", length = 200)
	public String getIdentityCode1() {
		return this.identityCode1;
	}

	public void setIdentityCode1(String identityCode1) {
		this.identityCode1 = identityCode1;
	}

	@Column(name = "LOG_DESCRIPTION", length = 200)
	public String getLogDescription() {
		return this.logDescription;
	}

	public void setLogDescription(String logDescription) {
		this.logDescription = logDescription;
	}

	@Column(name = "RELATED", nullable = false, length = 20)
	public String getRelated() {
		return this.related;
	}

	public void setRelated(String related) {
		this.related = related;
	}

}
