package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PurchaseOrderTempItemId generated by hbm2java
 */
@Embeddable
public class PurchaseOrderTempItemId implements java.io.Serializable {

	private String itemNo;
	private String unitCode;

	public PurchaseOrderTempItemId() {
	}

	public PurchaseOrderTempItemId(String itemNo, String unitCode) {
		this.itemNo = itemNo;
		this.unitCode = unitCode;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "UNIT_CODE", nullable = false, length = 20)
	public String getUnitCode() {
		return this.unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PurchaseOrderTempItemId))
			return false;
		PurchaseOrderTempItemId castOther = (PurchaseOrderTempItemId) other;

		return ((this.getItemNo() == castOther.getItemNo()) || (this
				.getItemNo() != null && castOther.getItemNo() != null && this
				.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getUnitCode() == castOther.getUnitCode()) || (this
						.getUnitCode() != null
						&& castOther.getUnitCode() != null && this
						.getUnitCode().equals(castOther.getUnitCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getUnitCode() == null ? 0 : this.getUnitCode().hashCode());
		return result;
	}

}
