package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PurchaseOrderItemId generated by hbm2java
 */
@Embeddable
public class PurchaseOrderItemId implements java.io.Serializable {

	private String phUnitNo;
	private String purchaseOrderNo;
	private String itemNo;

	public PurchaseOrderItemId() {
	}

	public PurchaseOrderItemId(String phUnitNo, String purchaseOrderNo,
			String itemNo) {
		this.phUnitNo = phUnitNo;
		this.purchaseOrderNo = purchaseOrderNo;
		this.itemNo = itemNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "PURCHASE_ORDER_NO", nullable = false, length = 20)
	public String getPurchaseOrderNo() {
		return this.purchaseOrderNo;
	}

	public void setPurchaseOrderNo(String purchaseOrderNo) {
		this.purchaseOrderNo = purchaseOrderNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PurchaseOrderItemId))
			return false;
		PurchaseOrderItemId castOther = (PurchaseOrderItemId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getPurchaseOrderNo() == castOther
						.getPurchaseOrderNo()) || (this.getPurchaseOrderNo() != null
						&& castOther.getPurchaseOrderNo() != null && this
						.getPurchaseOrderNo().equals(
								castOther.getPurchaseOrderNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null && castOther.getItemNo() != null && this
						.getItemNo().equals(castOther.getItemNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37
				* result
				+ (getPurchaseOrderNo() == null ? 0 : this.getPurchaseOrderNo()
						.hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		return result;
	}

}
