package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PurchaseOrderId generated by hbm2java
 */
@Embeddable
public class PurchaseOrderId implements java.io.Serializable {

	private String purchaseOrderNo;
	private String phUnitNo;

	public PurchaseOrderId() {
	}

	public PurchaseOrderId(String purchaseOrderNo, String phUnitNo) {
		this.purchaseOrderNo = purchaseOrderNo;
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "PURCHASE_ORDER_NO", nullable = false, length = 20)
	public String getPurchaseOrderNo() {
		return this.purchaseOrderNo;
	}

	public void setPurchaseOrderNo(String purchaseOrderNo) {
		this.purchaseOrderNo = purchaseOrderNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PurchaseOrderId))
			return false;
		PurchaseOrderId castOther = (PurchaseOrderId) other;

		return ((this.getPurchaseOrderNo() == castOther.getPurchaseOrderNo()) || (this
				.getPurchaseOrderNo() != null
				&& castOther.getPurchaseOrderNo() != null && this
				.getPurchaseOrderNo().equals(castOther.getPurchaseOrderNo())))
				&& ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
						.getPhUnitNo() != null
						&& castOther.getPhUnitNo() != null && this
						.getPhUnitNo().equals(castOther.getPhUnitNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPurchaseOrderNo() == null ? 0 : this.getPurchaseOrderNo()
						.hashCode());
		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		return result;
	}

}
