package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PurchaseOrder generated by hbm2java
 */
@Entity
@Table(name = "PURCHASE_ORDER")
public class PurchaseOrder implements java.io.Serializable {

	private PurchaseOrderId id;
	private PharmacyUnit pharmacyUnit;
	private Supplier supplier;
	private BigDecimal purchaseOrderType;
	private Date purchaseOrderDate;
	private BigDecimal printingStatus;
	private String createUserId;
	private String createUserIp;
	private String approvedUserId;
	private String approvedUserIp;
	private Date approvedDate;
	private BigDecimal netAmount;
	private BigDecimal aboutConsmp;
	private BigDecimal poStatus;
	private Set<Grn> grns = new HashSet<Grn>(0);
	private Set<PurchaseOrderItem> purchaseOrderItems = new HashSet<PurchaseOrderItem>(
			0);

	public PurchaseOrder() {
	}

	public PurchaseOrder(PurchaseOrderId id, PharmacyUnit pharmacyUnit,
			Supplier supplier, BigDecimal purchaseOrderType,
			Date purchaseOrderDate, BigDecimal printingStatus,
			String createUserId, String createUserIp, BigDecimal aboutConsmp,
			BigDecimal poStatus) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.supplier = supplier;
		this.purchaseOrderType = purchaseOrderType;
		this.purchaseOrderDate = purchaseOrderDate;
		this.printingStatus = printingStatus;
		this.createUserId = createUserId;
		this.createUserIp = createUserIp;
		this.aboutConsmp = aboutConsmp;
		this.poStatus = poStatus;
	}

	public PurchaseOrder(PurchaseOrderId id, PharmacyUnit pharmacyUnit,
			Supplier supplier, BigDecimal purchaseOrderType,
			Date purchaseOrderDate, BigDecimal printingStatus,
			String createUserId, String createUserIp, String approvedUserId,
			String approvedUserIp, Date approvedDate, BigDecimal netAmount,
			BigDecimal aboutConsmp, BigDecimal poStatus, Set<Grn> grns,
			Set<PurchaseOrderItem> purchaseOrderItems) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.supplier = supplier;
		this.purchaseOrderType = purchaseOrderType;
		this.purchaseOrderDate = purchaseOrderDate;
		this.printingStatus = printingStatus;
		this.createUserId = createUserId;
		this.createUserIp = createUserIp;
		this.approvedUserId = approvedUserId;
		this.approvedUserIp = approvedUserIp;
		this.approvedDate = approvedDate;
		this.netAmount = netAmount;
		this.aboutConsmp = aboutConsmp;
		this.poStatus = poStatus;
		this.grns = grns;
		this.purchaseOrderItems = purchaseOrderItems;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "purchaseOrderNo", column = @Column(name = "PURCHASE_ORDER_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)) })
	public PurchaseOrderId getId() {
		return this.id;
	}

	public void setId(PurchaseOrderId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIT_NO", nullable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "SUP_NO", referencedColumnName = "SUP_NO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "UNIT_NO", referencedColumnName = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false) })
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "PURCHASE_ORDER_TYPE", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPurchaseOrderType() {
		return this.purchaseOrderType;
	}

	public void setPurchaseOrderType(BigDecimal purchaseOrderType) {
		this.purchaseOrderType = purchaseOrderType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PURCHASE_ORDER_DATE", nullable = false, length = 7)
	public Date getPurchaseOrderDate() {
		return this.purchaseOrderDate;
	}

	public void setPurchaseOrderDate(Date purchaseOrderDate) {
		this.purchaseOrderDate = purchaseOrderDate;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "CREATE_USER_ID", nullable = false, length = 20)
	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "CREATE_USER_IP", nullable = false, length = 15)
	public String getCreateUserIp() {
		return this.createUserIp;
	}

	public void setCreateUserIp(String createUserIp) {
		this.createUserIp = createUserIp;
	}

	@Column(name = "APPROVED_USER_ID", length = 20)
	public String getApprovedUserId() {
		return this.approvedUserId;
	}

	public void setApprovedUserId(String approvedUserId) {
		this.approvedUserId = approvedUserId;
	}

	@Column(name = "APPROVED_USER_IP", length = 15)
	public String getApprovedUserIp() {
		return this.approvedUserIp;
	}

	public void setApprovedUserIp(String approvedUserIp) {
		this.approvedUserIp = approvedUserIp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "APPROVED_DATE", length = 7)
	public Date getApprovedDate() {
		return this.approvedDate;
	}

	public void setApprovedDate(Date approvedDate) {
		this.approvedDate = approvedDate;
	}

	@Column(name = "NET_AMOUNT", precision = 15)
	public BigDecimal getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(BigDecimal netAmount) {
		this.netAmount = netAmount;
	}

	@Column(name = "ABOUT_CONSMP", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAboutConsmp() {
		return this.aboutConsmp;
	}

	public void setAboutConsmp(BigDecimal aboutConsmp) {
		this.aboutConsmp = aboutConsmp;
	}

	@Column(name = "PO_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPoStatus() {
		return this.poStatus;
	}

	public void setPoStatus(BigDecimal poStatus) {
		this.poStatus = poStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purchaseOrder")
	public Set<Grn> getGrns() {
		return this.grns;
	}

	public void setGrns(Set<Grn> grns) {
		this.grns = grns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "purchaseOrder")
	public Set<PurchaseOrderItem> getPurchaseOrderItems() {
		return this.purchaseOrderItems;
	}

	public void setPurchaseOrderItems(Set<PurchaseOrderItem> purchaseOrderItems) {
		this.purchaseOrderItems = purchaseOrderItems;
	}

}
