package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelatedPharmacyForRequests generated by hbm2java
 */
@Entity
@Table(name = "RELATED_PHARMACY_FOR_REQUESTS")
public class RelatedPharmacyForRequests implements java.io.Serializable {

	private RelatedPharmacyForRequestsId id;
	private PharmacyUnit pharmacyUnitByPharmacyUnit1;
	private PharmacyUnit pharmacyUnitByPharmacyUnit2;
	private BigDecimal status;

	public RelatedPharmacyForRequests() {
	}

	public RelatedPharmacyForRequests(RelatedPharmacyForRequestsId id,
			PharmacyUnit pharmacyUnitByPharmacyUnit1,
			PharmacyUnit pharmacyUnitByPharmacyUnit2, BigDecimal status) {
		this.id = id;
		this.pharmacyUnitByPharmacyUnit1 = pharmacyUnitByPharmacyUnit1;
		this.pharmacyUnitByPharmacyUnit2 = pharmacyUnitByPharmacyUnit2;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pharmacyUnit1", column = @Column(name = "PHARMACY_UNIT_1", nullable = false, length = 20)),
			@AttributeOverride(name = "pharmacyUnit2", column = @Column(name = "PHARMACY_UNIT_2", nullable = false, length = 20)) })
	public RelatedPharmacyForRequestsId getId() {
		return this.id;
	}

	public void setId(RelatedPharmacyForRequestsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHARMACY_UNIT_1", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnitByPharmacyUnit1() {
		return this.pharmacyUnitByPharmacyUnit1;
	}

	public void setPharmacyUnitByPharmacyUnit1(
			PharmacyUnit pharmacyUnitByPharmacyUnit1) {
		this.pharmacyUnitByPharmacyUnit1 = pharmacyUnitByPharmacyUnit1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHARMACY_UNIT_2", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnitByPharmacyUnit2() {
		return this.pharmacyUnitByPharmacyUnit2;
	}

	public void setPharmacyUnitByPharmacyUnit2(
			PharmacyUnit pharmacyUnitByPharmacyUnit2) {
		this.pharmacyUnitByPharmacyUnit2 = pharmacyUnitByPharmacyUnit2;
	}

	@Column(name = "STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

}
