package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ReorderTempItemId generated by hbm2java
 */
@Embeddable
public class ReorderTempItemId implements java.io.Serializable {

	private String itemNo;
	private String unitCode;
	private String reqUnit;

	public ReorderTempItemId() {
	}

	public ReorderTempItemId(String itemNo, String unitCode, String reqUnit) {
		this.itemNo = itemNo;
		this.unitCode = unitCode;
		this.reqUnit = reqUnit;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "UNIT_CODE", nullable = false, length = 20)
	public String getUnitCode() {
		return this.unitCode;
	}

	public void setUnitCode(String unitCode) {
		this.unitCode = unitCode;
	}

	@Column(name = "REQ_UNIT", nullable = false, length = 20)
	public String getReqUnit() {
		return this.reqUnit;
	}

	public void setReqUnit(String reqUnit) {
		this.reqUnit = reqUnit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReorderTempItemId))
			return false;
		ReorderTempItemId castOther = (ReorderTempItemId) other;

		return ((this.getItemNo() == castOther.getItemNo()) || (this
				.getItemNo() != null && castOther.getItemNo() != null && this
				.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getUnitCode() == castOther.getUnitCode()) || (this
						.getUnitCode() != null
						&& castOther.getUnitCode() != null && this
						.getUnitCode().equals(castOther.getUnitCode())))
				&& ((this.getReqUnit() == castOther.getReqUnit()) || (this
						.getReqUnit() != null && castOther.getReqUnit() != null && this
						.getReqUnit().equals(castOther.getReqUnit())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getUnitCode() == null ? 0 : this.getUnitCode().hashCode());
		result = 37 * result
				+ (getReqUnit() == null ? 0 : this.getReqUnit().hashCode());
		return result;
	}

}
