package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServiceRefundCreditId generated by hbm2java
 */
@Embeddable
public class ServiceRefundCreditId implements java.io.Serializable {

	private String serviceRefNo;
	private String serviceCode;
	private String voucherNo;

	public ServiceRefundCreditId() {
	}

	public ServiceRefundCreditId(String serviceRefNo, String serviceCode,
			String voucherNo) {
		this.serviceRefNo = serviceRefNo;
		this.serviceCode = serviceCode;
		this.voucherNo = voucherNo;
	}

	@Column(name = "SERVICE_REF_NO", nullable = false, length = 20)
	public String getServiceRefNo() {
		return this.serviceRefNo;
	}

	public void setServiceRefNo(String serviceRefNo) {
		this.serviceRefNo = serviceRefNo;
	}

	@Column(name = "SERVICE_CODE", nullable = false, length = 40)
	public String getServiceCode() {
		return this.serviceCode;
	}

	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	@Column(name = "VOUCHER_NO", nullable = false, length = 20)
	public String getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiceRefundCreditId))
			return false;
		ServiceRefundCreditId castOther = (ServiceRefundCreditId) other;

		return ((this.getServiceRefNo() == castOther.getServiceRefNo()) || (this
				.getServiceRefNo() != null
				&& castOther.getServiceRefNo() != null && this
				.getServiceRefNo().equals(castOther.getServiceRefNo())))
				&& ((this.getServiceCode() == castOther.getServiceCode()) || (this
						.getServiceCode() != null
						&& castOther.getServiceCode() != null && this
						.getServiceCode().equals(castOther.getServiceCode())))
				&& ((this.getVoucherNo() == castOther.getVoucherNo()) || (this
						.getVoucherNo() != null
						&& castOther.getVoucherNo() != null && this
						.getVoucherNo().equals(castOther.getVoucherNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServiceRefNo() == null ? 0 : this.getServiceRefNo()
						.hashCode());
		result = 37
				* result
				+ (getServiceCode() == null ? 0 : this.getServiceCode()
						.hashCode());
		result = 37 * result
				+ (getVoucherNo() == null ? 0 : this.getVoucherNo().hashCode());
		return result;
	}

}
