package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServiceIssueSaleId generated by hbm2java
 */
@Embeddable
public class ServiceIssueSaleId implements java.io.Serializable {

	private String phUnitNo;
	private String unitServiceNo;
	private String serviceId;
	private String price;
	private String itemDiscount;
	private String minPrice;
	private Date isdate;

	public ServiceIssueSaleId() {
	}

	public ServiceIssueSaleId(String phUnitNo, String unitServiceNo) {
		this.phUnitNo = phUnitNo;
		this.unitServiceNo = unitServiceNo;
	}

	public ServiceIssueSaleId(String phUnitNo, String unitServiceNo,
			String serviceId, String price, String itemDiscount,
			String minPrice, Date isdate) {
		this.phUnitNo = phUnitNo;
		this.unitServiceNo = unitServiceNo;
		this.serviceId = serviceId;
		this.price = price;
		this.itemDiscount = itemDiscount;
		this.minPrice = minPrice;
		this.isdate = isdate;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "UNIT_SERVICE_NO", nullable = false, length = 20)
	public String getUnitServiceNo() {
		return this.unitServiceNo;
	}

	public void setUnitServiceNo(String unitServiceNo) {
		this.unitServiceNo = unitServiceNo;
	}

	@Column(name = "SERVICE_ID", length = 20)
	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "PRICE", length = 20)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "ITEM_DISCOUNT", length = 20)
	public String getItemDiscount() {
		return this.itemDiscount;
	}

	public void setItemDiscount(String itemDiscount) {
		this.itemDiscount = itemDiscount;
	}

	@Column(name = "MIN_PRICE", length = 20)
	public String getMinPrice() {
		return this.minPrice;
	}

	public void setMinPrice(String minPrice) {
		this.minPrice = minPrice;
	}

	@Column(name = "ISDATE", length = 7)
	public Date getIsdate() {
		return this.isdate;
	}

	public void setIsdate(Date isdate) {
		this.isdate = isdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiceIssueSaleId))
			return false;
		ServiceIssueSaleId castOther = (ServiceIssueSaleId) other;

		return ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
				.getPhUnitNo() != null && castOther.getPhUnitNo() != null && this
				.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getUnitServiceNo() == castOther.getUnitServiceNo()) || (this
						.getUnitServiceNo() != null
						&& castOther.getUnitServiceNo() != null && this
						.getUnitServiceNo()
						.equals(castOther.getUnitServiceNo())))
				&& ((this.getServiceId() == castOther.getServiceId()) || (this
						.getServiceId() != null
						&& castOther.getServiceId() != null && this
						.getServiceId().equals(castOther.getServiceId())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getItemDiscount() == castOther.getItemDiscount()) || (this
						.getItemDiscount() != null
						&& castOther.getItemDiscount() != null && this
						.getItemDiscount().equals(castOther.getItemDiscount())))
				&& ((this.getMinPrice() == castOther.getMinPrice()) || (this
						.getMinPrice() != null
						&& castOther.getMinPrice() != null && this
						.getMinPrice().equals(castOther.getMinPrice())))
				&& ((this.getIsdate() == castOther.getIsdate()) || (this
						.getIsdate() != null && castOther.getIsdate() != null && this
						.getIsdate().equals(castOther.getIsdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37
				* result
				+ (getUnitServiceNo() == null ? 0 : this.getUnitServiceNo()
						.hashCode());
		result = 37 * result
				+ (getServiceId() == null ? 0 : this.getServiceId().hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37
				* result
				+ (getItemDiscount() == null ? 0 : this.getItemDiscount()
						.hashCode());
		result = 37 * result
				+ (getMinPrice() == null ? 0 : this.getMinPrice().hashCode());
		result = 37 * result
				+ (getIsdate() == null ? 0 : this.getIsdate().hashCode());
		return result;
	}

}
