package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ServiceIssueSale generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_ISSUE_SALE")
public class ServiceIssueSale implements java.io.Serializable {

	private ServiceIssueSaleId id;

	public ServiceIssueSale() {
	}

	public ServiceIssueSale(ServiceIssueSaleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "unitServiceNo", column = @Column(name = "UNIT_SERVICE_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "serviceId", column = @Column(name = "SERVICE_ID", length = 20)),
			@AttributeOverride(name = "price", column = @Column(name = "PRICE", length = 20)),
			@AttributeOverride(name = "itemDiscount", column = @Column(name = "ITEM_DISCOUNT", length = 20)),
			@AttributeOverride(name = "minPrice", column = @Column(name = "MIN_PRICE", length = 20)),
			@AttributeOverride(name = "isdate", column = @Column(name = "ISDATE", length = 7)) })
	public ServiceIssueSaleId getId() {
		return this.id;
	}

	public void setId(ServiceIssueSaleId id) {
		this.id = id;
	}

}
