package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ServiceIsseCancelId generated by hbm2java
 */
@Embeddable
public class ServiceIsseCancelId implements java.io.Serializable {

	private String unitServiceNo;
	private String isseDate;
	private String userId;
	private String userIp;

	public ServiceIsseCancelId() {
	}

	public ServiceIsseCancelId(String unitServiceNo, String isseDate,
			String userId, String userIp) {
		this.unitServiceNo = unitServiceNo;
		this.isseDate = isseDate;
		this.userId = userId;
		this.userIp = userIp;
	}

	@Column(name = "UNIT_SERVICE_NO", length = 20)
	public String getUnitServiceNo() {
		return this.unitServiceNo;
	}

	public void setUnitServiceNo(String unitServiceNo) {
		this.unitServiceNo = unitServiceNo;
	}

	@Column(name = "ISSE_DATE", length = 20)
	public String getIsseDate() {
		return this.isseDate;
	}

	public void setIsseDate(String isseDate) {
		this.isseDate = isseDate;
	}

	@Column(name = "USER_ID", length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", length = 20)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ServiceIsseCancelId))
			return false;
		ServiceIsseCancelId castOther = (ServiceIsseCancelId) other;

		return ((this.getUnitServiceNo() == castOther.getUnitServiceNo()) || (this
				.getUnitServiceNo() != null
				&& castOther.getUnitServiceNo() != null && this
				.getUnitServiceNo().equals(castOther.getUnitServiceNo())))
				&& ((this.getIsseDate() == castOther.getIsseDate()) || (this
						.getIsseDate() != null
						&& castOther.getIsseDate() != null && this
						.getIsseDate().equals(castOther.getIsseDate())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserIp() == castOther.getUserIp()) || (this
						.getUserIp() != null && castOther.getUserIp() != null && this
						.getUserIp().equals(castOther.getUserIp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getUnitServiceNo() == null ? 0 : this.getUnitServiceNo()
						.hashCode());
		result = 37 * result
				+ (getIsseDate() == null ? 0 : this.getIsseDate().hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getUserIp() == null ? 0 : this.getUserIp().hashCode());
		return result;
	}

}
