package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ServiceIsseCancel generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_ISSE_CANCEL")
public class ServiceIsseCancel implements java.io.Serializable {

	private ServiceIsseCancelId id;

	public ServiceIsseCancel() {
	}

	public ServiceIsseCancel(ServiceIsseCancelId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "unitServiceNo", column = @Column(name = "UNIT_SERVICE_NO", length = 20)),
			@AttributeOverride(name = "isseDate", column = @Column(name = "ISSE_DATE", length = 20)),
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", length = 20)),
			@AttributeOverride(name = "userIp", column = @Column(name = "USER_IP", length = 20)) })
	public ServiceIsseCancelId getId() {
		return this.id;
	}

	public void setId(ServiceIsseCancelId id) {
		this.id = id;
	}

}
