package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ServiceRefundCredit generated by hbm2java
 */
@Entity
@Table(name = "SERVICE_REFUND_CREDIT")
public class ServiceRefundCredit implements java.io.Serializable {

	private ServiceRefundCreditId id;
	private BigDecimal refundAmount;
	private String userId;
	private Date txnDate;
	private Byte status;
	private String remarks;
	private String opdNo;

	public ServiceRefundCredit() {
	}

	public ServiceRefundCredit(ServiceRefundCreditId id) {
		this.id = id;
	}

	public ServiceRefundCredit(ServiceRefundCreditId id,
			BigDecimal refundAmount, String userId, Date txnDate, Byte status,
			String remarks, String opdNo) {
		this.id = id;
		this.refundAmount = refundAmount;
		this.userId = userId;
		this.txnDate = txnDate;
		this.status = status;
		this.remarks = remarks;
		this.opdNo = opdNo;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "serviceRefNo", column = @Column(name = "SERVICE_REF_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "serviceCode", column = @Column(name = "SERVICE_CODE", nullable = false, length = 40)),
			@AttributeOverride(name = "voucherNo", column = @Column(name = "VOUCHER_NO", nullable = false, length = 20)) })
	public ServiceRefundCreditId getId() {
		return this.id;
	}

	public void setId(ServiceRefundCreditId id) {
		this.id = id;
	}

	@Column(name = "REFUND_AMOUNT", precision = 20)
	public BigDecimal getRefundAmount() {
		return this.refundAmount;
	}

	public void setRefundAmount(BigDecimal refundAmount) {
		this.refundAmount = refundAmount;
	}

	@Column(name = "USER_ID", length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TXN_DATE", length = 7)
	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	@Column(name = "STATUS", precision = 2, scale = 0)
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "REMARKS", length = 100)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "OPD_NO", length = 20)
	public String getOpdNo() {
		return this.opdNo;
	}

	public void setOpdNo(String opdNo) {
		this.opdNo = opdNo;
	}

}
