package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StockValuationId generated by hbm2java
 */
@Embeddable
public class StockValuationId implements java.io.Serializable {

	private String unitNo;
	private String itemNo;
	private String grnNo;
	private Date valuationDate;

	public StockValuationId() {
	}

	public StockValuationId(String unitNo, String itemNo, String grnNo,
			Date valuationDate) {
		this.unitNo = unitNo;
		this.itemNo = itemNo;
		this.grnNo = grnNo;
		this.valuationDate = valuationDate;
	}

	@Column(name = "UNIT_NO", nullable = false, length = 20)
	public String getUnitNo() {
		return this.unitNo;
	}

	public void setUnitNo(String unitNo) {
		this.unitNo = unitNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "GRN_NO", nullable = false, length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

	@Column(name = "VALUATION_DATE", nullable = false, length = 7)
	public Date getValuationDate() {
		return this.valuationDate;
	}

	public void setValuationDate(Date valuationDate) {
		this.valuationDate = valuationDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StockValuationId))
			return false;
		StockValuationId castOther = (StockValuationId) other;

		return ((this.getUnitNo() == castOther.getUnitNo()) || (this
				.getUnitNo() != null && castOther.getUnitNo() != null && this
				.getUnitNo().equals(castOther.getUnitNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null && castOther.getItemNo() != null && this
						.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getGrnNo() == castOther.getGrnNo()) || (this
						.getGrnNo() != null && castOther.getGrnNo() != null && this
						.getGrnNo().equals(castOther.getGrnNo())))
				&& ((this.getValuationDate() == castOther.getValuationDate()) || (this
						.getValuationDate() != null
						&& castOther.getValuationDate() != null && this
						.getValuationDate()
						.equals(castOther.getValuationDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUnitNo() == null ? 0 : this.getUnitNo().hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getGrnNo() == null ? 0 : this.getGrnNo().hashCode());
		result = 37
				* result
				+ (getValuationDate() == null ? 0 : this.getValuationDate()
						.hashCode());
		return result;
	}

}
