package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * StockValuation generated by hbm2java
 */
@Entity
@Table(name = "STOCK_VALUATION")
public class StockValuation implements java.io.Serializable {

	private StockValuationId id;
	private double quantity;
	private double costPrice;
	private double retailPrice;

	public StockValuation() {
	}

	public StockValuation(StockValuationId id, double quantity,
			double costPrice, double retailPrice) {
		this.id = id;
		this.quantity = quantity;
		this.costPrice = costPrice;
		this.retailPrice = retailPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "unitNo", column = @Column(name = "UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "valuationDate", column = @Column(name = "VALUATION_DATE", nullable = false, length = 7)) })
	public StockValuationId getId() {
		return this.id;
	}

	public void setId(StockValuationId id) {
		this.id = id;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "COST_PRICE", nullable = false, precision = 126, scale = 0)
	public double getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(double costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "RETAIL_PRICE", nullable = false, precision = 126, scale = 0)
	public double getRetailPrice() {
		return this.retailPrice;
	}

	public void setRetailPrice(double retailPrice) {
		this.retailPrice = retailPrice;
	}

}
