package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SupplierReturnItemId generated by hbm2java
 */
@Embeddable
public class SupplierReturnItemId implements java.io.Serializable {

	private String supplierReturnNo;
	private String phUnitNo;
	private String itemNo;
	private String grnNo;

	public SupplierReturnItemId() {
	}

	public SupplierReturnItemId(String supplierReturnNo, String phUnitNo,
			String itemNo, String grnNo) {
		this.supplierReturnNo = supplierReturnNo;
		this.phUnitNo = phUnitNo;
		this.itemNo = itemNo;
		this.grnNo = grnNo;
	}

	@Column(name = "SUPPLIER_RETURN_NO", nullable = false, length = 20)
	public String getSupplierReturnNo() {
		return this.supplierReturnNo;
	}

	public void setSupplierReturnNo(String supplierReturnNo) {
		this.supplierReturnNo = supplierReturnNo;
	}

	@Column(name = "PH_UNIT_NO", nullable = false, length = 20)
	public String getPhUnitNo() {
		return this.phUnitNo;
	}

	public void setPhUnitNo(String phUnitNo) {
		this.phUnitNo = phUnitNo;
	}

	@Column(name = "ITEM_NO", nullable = false, length = 20)
	public String getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(String itemNo) {
		this.itemNo = itemNo;
	}

	@Column(name = "GRN_NO", nullable = false, length = 20)
	public String getGrnNo() {
		return this.grnNo;
	}

	public void setGrnNo(String grnNo) {
		this.grnNo = grnNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SupplierReturnItemId))
			return false;
		SupplierReturnItemId castOther = (SupplierReturnItemId) other;

		return ((this.getSupplierReturnNo() == castOther.getSupplierReturnNo()) || (this
				.getSupplierReturnNo() != null
				&& castOther.getSupplierReturnNo() != null && this
				.getSupplierReturnNo().equals(castOther.getSupplierReturnNo())))
				&& ((this.getPhUnitNo() == castOther.getPhUnitNo()) || (this
						.getPhUnitNo() != null
						&& castOther.getPhUnitNo() != null && this
						.getPhUnitNo().equals(castOther.getPhUnitNo())))
				&& ((this.getItemNo() == castOther.getItemNo()) || (this
						.getItemNo() != null && castOther.getItemNo() != null && this
						.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getGrnNo() == castOther.getGrnNo()) || (this
						.getGrnNo() != null && castOther.getGrnNo() != null && this
						.getGrnNo().equals(castOther.getGrnNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSupplierReturnNo() == null ? 0 : this
						.getSupplierReturnNo().hashCode());
		result = 37 * result
				+ (getPhUnitNo() == null ? 0 : this.getPhUnitNo().hashCode());
		result = 37 * result
				+ (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result
				+ (getGrnNo() == null ? 0 : this.getGrnNo().hashCode());
		return result;
	}

}
