package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * SupplierReturnItem generated by hbm2java
 */
@Entity
@Table(name = "SUPPLIER_RETURN_ITEM")
public class SupplierReturnItem implements java.io.Serializable {

	private SupplierReturnItemId id;
	private double quantity;
	private BigDecimal netAmount;
	private BigDecimal costPrice;

	public SupplierReturnItem() {
	}

	public SupplierReturnItem(SupplierReturnItemId id, double quantity,
			BigDecimal netAmount, BigDecimal costPrice) {
		this.id = id;
		this.quantity = quantity;
		this.netAmount = netAmount;
		this.costPrice = costPrice;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "supplierReturnNo", column = @Column(name = "SUPPLIER_RETURN_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "itemNo", column = @Column(name = "ITEM_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "grnNo", column = @Column(name = "GRN_NO", nullable = false, length = 20)) })
	public SupplierReturnItemId getId() {
		return this.id;
	}

	public void setId(SupplierReturnItemId id) {
		this.id = id;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	@Column(name = "NET_AMOUNT", nullable = false, precision = 10)
	public BigDecimal getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(BigDecimal netAmount) {
		this.netAmount = netAmount;
	}

	@Column(name = "COST_PRICE", nullable = false, precision = 10)
	public BigDecimal getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(BigDecimal costPrice) {
		this.costPrice = costPrice;
	}

}
