package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "SUPPLIER")
public class Supplier implements java.io.Serializable {

	private SupplierId id;
	private PharmacyUnit pharmacyUnit;
	private Supplier supplier;
	private String supName;
	private String payeeName;
	private String telephone;
	private String fax;
	private String addressNo;
	private String addressStreet;
	private String addressTown;
	private Date supRegisteredDate;
	private String userId;
	private String userIp;
	private BigDecimal currentStatus;
	private String oldCode;
	private String EMail;
	private String webAdd;
	private Integer creditDueDates;
	private Set<Grn> grns = new HashSet<Grn>(0);
	private Set<DrugItemPharmacyUnit> drugItemPharmacyUnits = new HashSet<DrugItemPharmacyUnit>(
			0);
	private Set<Supplier> suppliers = new HashSet<Supplier>(0);
	private Set<PurchaseOrder> purchaseOrders = new HashSet<PurchaseOrder>(0);

	public Supplier() {
	}

	public Supplier(SupplierId id, PharmacyUnit pharmacyUnit, String supName,
			String payeeName, String addressNo, Date supRegisteredDate,
			String userId, String userIp, BigDecimal currentStatus) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.supName = supName;
		this.payeeName = payeeName;
		this.addressNo = addressNo;
		this.supRegisteredDate = supRegisteredDate;
		this.userId = userId;
		this.userIp = userIp;
		this.currentStatus = currentStatus;
	}

	public Supplier(SupplierId id, PharmacyUnit pharmacyUnit,
			Supplier supplier, String supName, String payeeName,
			String telephone, String fax, String addressNo,
			String addressStreet, String addressTown, Date supRegisteredDate,
			String userId, String userIp, BigDecimal currentStatus,
			String oldCode, String EMail, String webAdd,
			Integer creditDueDates, Set<Grn> grns,
			Set<DrugItemPharmacyUnit> drugItemPharmacyUnits,
			Set<Supplier> suppliers, Set<PurchaseOrder> purchaseOrders) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.supplier = supplier;
		this.supName = supName;
		this.payeeName = payeeName;
		this.telephone = telephone;
		this.fax = fax;
		this.addressNo = addressNo;
		this.addressStreet = addressStreet;
		this.addressTown = addressTown;
		this.supRegisteredDate = supRegisteredDate;
		this.userId = userId;
		this.userIp = userIp;
		this.currentStatus = currentStatus;
		this.oldCode = oldCode;
		this.EMail = EMail;
		this.webAdd = webAdd;
		this.creditDueDates = creditDueDates;
		this.grns = grns;
		this.drugItemPharmacyUnits = drugItemPharmacyUnits;
		this.suppliers = suppliers;
		this.purchaseOrders = purchaseOrders;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "supNo", column = @Column(name = "SUP_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "phUnitNo", column = @Column(name = "PH_UNIT_NO", nullable = false, length = 20)) })
	public SupplierId getId() {
		return this.id;
	}

	public void setId(SupplierId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "REF_SUP_NO", referencedColumnName = "SUP_NO"),
			@JoinColumn(name = "UNIT_NO", referencedColumnName = "PH_UNIT_NO") })
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "SUP_NAME", nullable = false, length = 200)
	public String getSupName() {
		return this.supName;
	}

	public void setSupName(String supName) {
		this.supName = supName;
	}

	@Column(name = "PAYEE_NAME", nullable = false, length = 200)
	public String getPayeeName() {
		return this.payeeName;
	}

	public void setPayeeName(String payeeName) {
		this.payeeName = payeeName;
	}

	@Column(name = "TELEPHONE", length = 10)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "FAX", length = 10)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "ADDRESS_NO", nullable = false, length = 200)
	public String getAddressNo() {
		return this.addressNo;
	}

	public void setAddressNo(String addressNo) {
		this.addressNo = addressNo;
	}

	@Column(name = "ADDRESS_STREET", length = 100)
	public String getAddressStreet() {
		return this.addressStreet;
	}

	public void setAddressStreet(String addressStreet) {
		this.addressStreet = addressStreet;
	}

	@Column(name = "ADDRESS_TOWN", length = 100)
	public String getAddressTown() {
		return this.addressTown;
	}

	public void setAddressTown(String addressTown) {
		this.addressTown = addressTown;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUP_REGISTERED_DATE", nullable = false, length = 7)
	public Date getSupRegisteredDate() {
		return this.supRegisteredDate;
	}

	public void setSupRegisteredDate(Date supRegisteredDate) {
		this.supRegisteredDate = supRegisteredDate;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	@Column(name = "CURRENT_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getCurrentStatus() {
		return this.currentStatus;
	}

	public void setCurrentStatus(BigDecimal currentStatus) {
		this.currentStatus = currentStatus;
	}

	@Column(name = "OLD_CODE", length = 20)
	public String getOldCode() {
		return this.oldCode;
	}

	public void setOldCode(String oldCode) {
		this.oldCode = oldCode;
	}

	@Column(name = "E_MAIL", length = 200)
	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	@Column(name = "WEB_ADD", length = 200)
	public String getWebAdd() {
		return this.webAdd;
	}

	public void setWebAdd(String webAdd) {
		this.webAdd = webAdd;
	}

	@Column(name = "CREDIT_DUE_DATES", precision = 5, scale = 0)
	public Integer getCreditDueDates() {
		return this.creditDueDates;
	}

	public void setCreditDueDates(Integer creditDueDates) {
		this.creditDueDates = creditDueDates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<Grn> getGrns() {
		return this.grns;
	}

	public void setGrns(Set<Grn> grns) {
		this.grns = grns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<DrugItemPharmacyUnit> getDrugItemPharmacyUnits() {
		return this.drugItemPharmacyUnits;
	}

	public void setDrugItemPharmacyUnits(
			Set<DrugItemPharmacyUnit> drugItemPharmacyUnits) {
		this.drugItemPharmacyUnits = drugItemPharmacyUnits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<Supplier> getSuppliers() {
		return this.suppliers;
	}

	public void setSuppliers(Set<Supplier> suppliers) {
		this.suppliers = suppliers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<PurchaseOrder> getPurchaseOrders() {
		return this.purchaseOrders;
	}

	public void setPurchaseOrders(Set<PurchaseOrder> purchaseOrders) {
		this.purchaseOrders = purchaseOrders;
	}

}
