package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SupplierReturnCancel generated by hbm2java
 */
@Entity
@Table(name = "SUPPLIER_RETURN_CANCEL")
public class SupplierReturnCancel implements java.io.Serializable {

	private String supplierReturnCancelNo;
	private String supplierReturnNo;
	private Date supplierReturnCancelDate;
	private BigDecimal printingStatus;
	private String userId;
	private String userIp;

	public SupplierReturnCancel() {
	}

	public SupplierReturnCancel(String supplierReturnCancelNo,
			String supplierReturnNo, Date supplierReturnCancelDate,
			BigDecimal printingStatus, String userId, String userIp) {
		this.supplierReturnCancelNo = supplierReturnCancelNo;
		this.supplierReturnNo = supplierReturnNo;
		this.supplierReturnCancelDate = supplierReturnCancelDate;
		this.printingStatus = printingStatus;
		this.userId = userId;
		this.userIp = userIp;
	}

	@Id
	@Column(name = "SUPPLIER_RETURN_CANCEL_NO", unique = true, nullable = false, length = 20)
	public String getSupplierReturnCancelNo() {
		return this.supplierReturnCancelNo;
	}

	public void setSupplierReturnCancelNo(String supplierReturnCancelNo) {
		this.supplierReturnCancelNo = supplierReturnCancelNo;
	}

	@Column(name = "SUPPLIER_RETURN_NO", nullable = false, length = 20)
	public String getSupplierReturnNo() {
		return this.supplierReturnNo;
	}

	public void setSupplierReturnNo(String supplierReturnNo) {
		this.supplierReturnNo = supplierReturnNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUPPLIER_RETURN_CANCEL_DATE", nullable = false, length = 7)
	public Date getSupplierReturnCancelDate() {
		return this.supplierReturnCancelDate;
	}

	public void setSupplierReturnCancelDate(Date supplierReturnCancelDate) {
		this.supplierReturnCancelDate = supplierReturnCancelDate;
	}

	@Column(name = "PRINTING_STATUS", nullable = false, precision = 38, scale = 0)
	public BigDecimal getPrintingStatus() {
		return this.printingStatus;
	}

	public void setPrintingStatus(BigDecimal printingStatus) {
		this.printingStatus = printingStatus;
	}

	@Column(name = "USER_ID", nullable = false, length = 20)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "USER_IP", nullable = false, length = 15)
	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

}
