package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemModules generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_MODULES")
public class SystemModules implements java.io.Serializable {

	private String moduleId;
	private String moduleName;
	private String description;
	private BigDecimal currentStatus;
	private String defaultTheme;

	public SystemModules() {
	}

	public SystemModules(String moduleId, String moduleName,
			BigDecimal currentStatus) {
		this.moduleId = moduleId;
		this.moduleName = moduleName;
		this.currentStatus = currentStatus;
	}

	public SystemModules(String moduleId, String moduleName,
			String description, BigDecimal currentStatus, String defaultTheme) {
		this.moduleId = moduleId;
		this.moduleName = moduleName;
		this.description = description;
		this.currentStatus = currentStatus;
		this.defaultTheme = defaultTheme;
	}

	@Id
	@Column(name = "MODULE_ID", unique = true, nullable = false, length = 5)
	public String getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "MODULE_NAME", nullable = false, length = 50)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Column(name = "DESCRIPTION", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "CURRENT_STATUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCurrentStatus() {
		return this.currentStatus;
	}

	public void setCurrentStatus(BigDecimal currentStatus) {
		this.currentStatus = currentStatus;
	}

	@Column(name = "DEFAULT_THEME", length = 5)
	public String getDefaultTheme() {
		return this.defaultTheme;
	}

	public void setDefaultTheme(String defaultTheme) {
		this.defaultTheme = defaultTheme;
	}

}
