package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemFunctions generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_FUNCTIONS")
public class SystemFunctions implements java.io.Serializable {

	private String functionId;
	private String functionName;
	private String url;
	private Date txnDate;
	private Boolean status;
	private String functionCategory;
	private Short showOrder;
	private String functionSubCategory;
	private Boolean functionType;
	private String moduleId;
	private Set<SystemUserFunctions> systemUserFunctionses = new HashSet<SystemUserFunctions>(
			0);

	public SystemFunctions() {
	}

	public SystemFunctions(String functionId, String moduleId) {
		this.functionId = functionId;
		this.moduleId = moduleId;
	}

	public SystemFunctions(String functionId, String functionName, String url,
			Date txnDate, Boolean status, String functionCategory,
			Short showOrder, String functionSubCategory, Boolean functionType,
			String moduleId, Set<SystemUserFunctions> systemUserFunctionses) {
		this.functionId = functionId;
		this.functionName = functionName;
		this.url = url;
		this.txnDate = txnDate;
		this.status = status;
		this.functionCategory = functionCategory;
		this.showOrder = showOrder;
		this.functionSubCategory = functionSubCategory;
		this.functionType = functionType;
		this.moduleId = moduleId;
		this.systemUserFunctionses = systemUserFunctionses;
	}

	@Id
	@Column(name = "FUNCTION_ID", unique = true, nullable = false, length = 10)
	public String getFunctionId() {
		return this.functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	@Column(name = "FUNCTION_NAME", length = 200)
	public String getFunctionName() {
		return this.functionName;
	}

	public void setFunctionName(String functionName) {
		this.functionName = functionName;
	}

	@Column(name = "URL", length = 200)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TXN_DATE", length = 7)
	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	@Column(name = "STATUS", precision = 1, scale = 0)
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "FUNCTION_CATEGORY", length = 10)
	public String getFunctionCategory() {
		return this.functionCategory;
	}

	public void setFunctionCategory(String functionCategory) {
		this.functionCategory = functionCategory;
	}

	@Column(name = "SHOW_ORDER", precision = 3, scale = 0)
	public Short getShowOrder() {
		return this.showOrder;
	}

	public void setShowOrder(Short showOrder) {
		this.showOrder = showOrder;
	}

	@Column(name = "FUNCTION_SUB_CATEGORY", length = 10)
	public String getFunctionSubCategory() {
		return this.functionSubCategory;
	}

	public void setFunctionSubCategory(String functionSubCategory) {
		this.functionSubCategory = functionSubCategory;
	}

	@Column(name = "FUNCTION_TYPE", precision = 1, scale = 0)
	public Boolean getFunctionType() {
		return this.functionType;
	}

	public void setFunctionType(Boolean functionType) {
		this.functionType = functionType;
	}

	@Column(name = "MODULE_ID", nullable = false, length = 5)
	public String getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemFunctions")
	public Set<SystemUserFunctions> getSystemUserFunctionses() {
		return this.systemUserFunctionses;
	}

	public void setSystemUserFunctionses(
			Set<SystemUserFunctions> systemUserFunctionses) {
		this.systemUserFunctionses = systemUserFunctionses;
	}

}
