package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemVariable generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_VARIABLE")
public class SystemVariable implements java.io.Serializable {

	private BigDecimal idx;
	private BigDecimal discVal;

	public SystemVariable() {
	}

	public SystemVariable(BigDecimal idx, BigDecimal discVal) {
		this.idx = idx;
		this.discVal = discVal;
	}

	@Id
	@Column(name = "IDX", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdx() {
		return this.idx;
	}

	public void setIdx(BigDecimal idx) {
		this.idx = idx;
	}

	@Column(name = "DISC_VAL", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDiscVal() {
		return this.discVal;
	}

	public void setDiscVal(BigDecimal discVal) {
		this.discVal = discVal;
	}

}
