package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemFuncSubCategories generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_FUNC_SUB_CATEGORIES")
public class SystemFuncSubCategories implements java.io.Serializable {

	private String subCatId;
	private String subCatName;

	public SystemFuncSubCategories() {
	}

	public SystemFuncSubCategories(String subCatId) {
		this.subCatId = subCatId;
	}

	public SystemFuncSubCategories(String subCatId, String subCatName) {
		this.subCatId = subCatId;
		this.subCatName = subCatName;
	}

	@Id
	@Column(name = "SUB_CAT_ID", unique = true, nullable = false, length = 10)
	public String getSubCatId() {
		return this.subCatId;
	}

	public void setSubCatId(String subCatId) {
		this.subCatId = subCatId;
	}

	@Column(name = "SUB_CAT_NAME", length = 100)
	public String getSubCatName() {
		return this.subCatName;
	}

	public void setSubCatName(String subCatName) {
		this.subCatName = subCatName;
	}

}
