package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SystemUserUnitId generated by hbm2java
 */
@Embeddable
public class SystemUserUnitId implements java.io.Serializable {

	private String userName;
	private String unitId;

	public SystemUserUnitId() {
	}

	public SystemUserUnitId(String userName, String unitId) {
		this.userName = userName;
		this.unitId = unitId;
	}

	@Column(name = "USER_NAME", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "UNIT_ID", nullable = false, length = 20)
	public String getUnitId() {
		return this.unitId;
	}

	public void setUnitId(String unitId) {
		this.unitId = unitId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SystemUserUnitId))
			return false;
		SystemUserUnitId castOther = (SystemUserUnitId) other;

		return ((this.getUserName() == castOther.getUserName()) || (this
				.getUserName() != null && castOther.getUserName() != null && this
				.getUserName().equals(castOther.getUserName())))
				&& ((this.getUnitId() == castOther.getUnitId()) || (this
						.getUnitId() != null && castOther.getUnitId() != null && this
						.getUnitId().equals(castOther.getUnitId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result
				+ (getUnitId() == null ? 0 : this.getUnitId().hashCode());
		return result;
	}

}
