package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemLogin generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_LOGIN")
public class SystemLogin extends DomainDefault  implements java.io.Serializable 
{

	/**
	 * 
	 */
	
	private static final long serialVersionUID = 1L;
	
	private String userName;
	private Theme theme;
	private PharmacyUnit pharmacyUnit;
	private String firstName;
	private String lastName;
	private BigDecimal userType;
	private String txnUser;
	private String txnIp;
	private Date txnDate;
	private BigDecimal status;
	private String accessId;
	private String securityCode;
	private Set<SystemUserFunctions> systemUserFunctionses = new HashSet<SystemUserFunctions>(0);
	private Set<SystemUserUnit> systemUserUnits = new HashSet<SystemUserUnit>(0);

	public SystemLogin() {
	}

	public SystemLogin(String userName, Theme theme, PharmacyUnit pharmacyUnit,
			String lastName, BigDecimal userType, String txnUser, String txnIp,
			Date txnDate, BigDecimal status, String accessId) {
		this.userName = userName;
		this.theme = theme;
		this.pharmacyUnit = pharmacyUnit;
		this.lastName = lastName;
		this.userType = userType;
		this.txnUser = txnUser;
		this.txnIp = txnIp;
		this.txnDate = txnDate;
		this.status = status;
		this.accessId = accessId;
	}

	public SystemLogin(String userName, Theme theme, PharmacyUnit pharmacyUnit,
			String firstName, String lastName, BigDecimal userType,
			String txnUser, String txnIp, Date txnDate, BigDecimal status,
			String accessId, String securityCode,
			Set<SystemUserFunctions> systemUserFunctionses,
			Set<SystemUserUnit> systemUserUnits) {
		this.userName = userName;
		this.theme = theme;
		this.pharmacyUnit = pharmacyUnit;
		this.firstName = firstName;
		this.lastName = lastName;
		this.userType = userType;
		this.txnUser = txnUser;
		this.txnIp = txnIp;
		this.txnDate = txnDate;
		this.status = status;
		this.accessId = accessId;
		this.securityCode = securityCode;
		this.systemUserFunctionses = systemUserFunctionses;
		this.systemUserUnits = systemUserUnits;
	}

	@Id
	@Column(name = "USER_NAME", unique = true, nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "THEME_CODE", nullable = false)
	public Theme getTheme() {
		return this.theme;
	}

	public void setTheme(Theme theme) {
		this.theme = theme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_NO", nullable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Column(name = "FIRST_NAME", length = 200)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", nullable = false, length = 200)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "USER_TYPE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getUserType() {
		return this.userType;
	}

	public void setUserType(BigDecimal userType) {
		this.userType = userType;
	}

	@Column(name = "TXN_USER", nullable = false, length = 50)
	public String getTxnUser() {
		return this.txnUser;
	}

	public void setTxnUser(String txnUser) {
		this.txnUser = txnUser;
	}

	@Column(name = "TXN_IP", nullable = false, length = 50)
	public String getTxnIp() {
		return this.txnIp;
	}

	public void setTxnIp(String txnIp) {
		this.txnIp = txnIp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TXN_DATE", nullable = false, length = 7)
	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	@Column(name = "STATUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

	@Column(name = "ACCESS_ID", nullable = false, length = 100)
	public String getAccessId() {
		return this.accessId;
	}

	public void setAccessId(String accessId) {
		this.accessId = accessId;
	}

	@Column(name = "SECURITY_CODE", length = 100)
	public String getSecurityCode() {
		return this.securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemLogin")
	public Set<SystemUserFunctions> getSystemUserFunctionses() {
		return this.systemUserFunctionses;
	}

	public void setSystemUserFunctionses(
			Set<SystemUserFunctions> systemUserFunctionses) {
		this.systemUserFunctionses = systemUserFunctionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemLogin")
	public Set<SystemUserUnit> getSystemUserUnits() {
		return this.systemUserUnits;
	}

	public void setSystemUserUnits(Set<SystemUserUnit> systemUserUnits) {
		this.systemUserUnits = systemUserUnits;
	}

}
