package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemFuncCategories generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_FUNC_CATEGORIES")
public class SystemFuncCategories implements java.io.Serializable {

	private String categoryId;
	private String categoryName;

	public SystemFuncCategories() {
	}

	public SystemFuncCategories(String categoryId) {
		this.categoryId = categoryId;
	}

	public SystemFuncCategories(String categoryId, String categoryName) {
		this.categoryId = categoryId;
		this.categoryName = categoryName;
	}

	@Id
	@Column(name = "CATEGORY_ID", unique = true, nullable = false, length = 5)
	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "CATEGORY_NAME", length = 100)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

}
