package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemUserFunctions generated by hbm2java
 */
@Entity
@Table(name = "SYSTEM_USER_FUNCTIONS")
public class SystemUserFunctions implements java.io.Serializable {

	private SystemUserFunctionsId id;
	private SystemFunctions systemFunctions;
	private SystemLogin systemLogin;
	private String txnId;
	private String txnIp;
	private Date txnDate;
	private BigDecimal status;

	public SystemUserFunctions() {
	}

	public SystemUserFunctions(SystemUserFunctionsId id,
			SystemFunctions systemFunctions, SystemLogin systemLogin,
			String txnId, String txnIp, Date txnDate, BigDecimal status) {
		this.id = id;
		this.systemFunctions = systemFunctions;
		this.systemLogin = systemLogin;
		this.txnId = txnId;
		this.txnIp = txnIp;
		this.txnDate = txnDate;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userName", column = @Column(name = "USER_NAME", nullable = false, length = 50)),
			@AttributeOverride(name = "functionId", column = @Column(name = "FUNCTION_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "unitId", column = @Column(name = "UNIT_ID", nullable = false, length = 50)) })
	public SystemUserFunctionsId getId() {
		return this.id;
	}

	public void setId(SystemUserFunctionsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FUNCTION_ID", nullable = false, insertable = false, updatable = false)
	public SystemFunctions getSystemFunctions() {
		return this.systemFunctions;
	}

	public void setSystemFunctions(SystemFunctions systemFunctions) {
		this.systemFunctions = systemFunctions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USER_NAME", nullable = false, insertable = false, updatable = false)
	public SystemLogin getSystemLogin() {
		return this.systemLogin;
	}

	public void setSystemLogin(SystemLogin systemLogin) {
		this.systemLogin = systemLogin;
	}

	@Column(name = "TXN_ID", nullable = false, length = 50)
	public String getTxnId() {
		return this.txnId;
	}

	public void setTxnId(String txnId) {
		this.txnId = txnId;
	}

	@Column(name = "TXN_IP", nullable = false, length = 50)
	public String getTxnIp() {
		return this.txnIp;
	}

	public void setTxnIp(String txnIp) {
		this.txnIp = txnIp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TXN_DATE", nullable = false, length = 7)
	public Date getTxnDate() {
		return this.txnDate;
	}

	public void setTxnDate(Date txnDate) {
		this.txnDate = txnDate;
	}

	@Column(name = "STATUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getStatus() {
		return this.status;
	}

	public void setStatus(BigDecimal status) {
		this.status = status;
	}

}
