package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TempQuantityId generated by hbm2java
 */
@Embeddable
public class TempQuantityId implements java.io.Serializable {

	private String itemCode;
	private String unitNo;

	public TempQuantityId() {
	}

	public TempQuantityId(String itemCode, String unitNo) {
		this.itemCode = itemCode;
		this.unitNo = unitNo;
	}

	@Column(name = "ITEM_CODE", nullable = false, length = 20)
	public String getItemCode() {
		return this.itemCode;
	}

	public void setItemCode(String itemCode) {
		this.itemCode = itemCode;
	}

	@Column(name = "UNIT_NO", nullable = false, length = 20)
	public String getUnitNo() {
		return this.unitNo;
	}

	public void setUnitNo(String unitNo) {
		this.unitNo = unitNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TempQuantityId))
			return false;
		TempQuantityId castOther = (TempQuantityId) other;

		return ((this.getItemCode() == castOther.getItemCode()) || (this
				.getItemCode() != null && castOther.getItemCode() != null && this
				.getItemCode().equals(castOther.getItemCode())))
				&& ((this.getUnitNo() == castOther.getUnitNo()) || (this
						.getUnitNo() != null && castOther.getUnitNo() != null && this
						.getUnitNo().equals(castOther.getUnitNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getItemCode() == null ? 0 : this.getItemCode().hashCode());
		result = 37 * result
				+ (getUnitNo() == null ? 0 : this.getUnitNo().hashCode());
		return result;
	}

}
