package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TempQuantity generated by hbm2java
 */
@Entity
@Table(name = "TEMP_QUANTITY")
public class TempQuantity implements java.io.Serializable {

	private TempQuantityId id;
	private PharmacyUnit pharmacyUnit;
	private DrugItem drugItem;
	private double quantity;

	public TempQuantity() {
	}

	public TempQuantity(TempQuantityId id, PharmacyUnit pharmacyUnit,
			DrugItem drugItem, double quantity) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.drugItem = drugItem;
		this.quantity = quantity;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "itemCode", column = @Column(name = "ITEM_CODE", nullable = false, length = 20)),
			@AttributeOverride(name = "unitNo", column = @Column(name = "UNIT_NO", nullable = false, length = 20)) })
	public TempQuantityId getId() {
		return this.id;
	}

	public void setId(TempQuantityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNIT_NO", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_CODE", nullable = false, insertable = false, updatable = false)
	public DrugItem getDrugItem() {
		return this.drugItem;
	}

	public void setDrugItem(DrugItem drugItem) {
		this.drugItem = drugItem;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 126, scale = 0)
	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

}
