package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TestPhService generated by hbm2java
 */
@Entity
@Table(name = "TEST_PH_SERVICE")
public class TestPhService implements java.io.Serializable {

	private TestPhServiceId id;
	private PharmacyUnit pharmacyUnit;
	private String serviceDisc;
	private BigDecimal activeStatus;
	private String minVal;

	public TestPhService() {
	}

	public TestPhService(TestPhServiceId id, PharmacyUnit pharmacyUnit) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
	}

	public TestPhService(TestPhServiceId id, PharmacyUnit pharmacyUnit,
			String serviceDisc, BigDecimal activeStatus, String minVal) {
		this.id = id;
		this.pharmacyUnit = pharmacyUnit;
		this.serviceDisc = serviceDisc;
		this.activeStatus = activeStatus;
		this.minVal = minVal;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "phUnitId", column = @Column(name = "PH_UNIT_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "serviceId", column = @Column(name = "SERVICE_ID", nullable = false, length = 20)) })
	public TestPhServiceId getId() {
		return this.id;
	}

	public void setId(TestPhServiceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PH_UNIT_ID", nullable = false, insertable = false, updatable = false)
	public PharmacyUnit getPharmacyUnit() {
		return this.pharmacyUnit;
	}

	public void setPharmacyUnit(PharmacyUnit pharmacyUnit) {
		this.pharmacyUnit = pharmacyUnit;
	}

	@Column(name = "SERVICE_DISC", length = 20)
	public String getServiceDisc() {
		return this.serviceDisc;
	}

	public void setServiceDisc(String serviceDisc) {
		this.serviceDisc = serviceDisc;
	}

	@Column(name = "ACTIVE_STATUS", precision = 22, scale = 0)
	public BigDecimal getActiveStatus() {
		return this.activeStatus;
	}

	public void setActiveStatus(BigDecimal activeStatus) {
		this.activeStatus = activeStatus;
	}

	@Column(name = "MIN_VAL", length = 20)
	public String getMinVal() {
		return this.minVal;
	}

	public void setMinVal(String minVal) {
		this.minVal = minVal;
	}

}
