package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TestPhServiceId generated by hbm2java
 */
@Embeddable
public class TestPhServiceId implements java.io.Serializable {

	private String phUnitId;
	private String serviceId;

	public TestPhServiceId() {
	}

	public TestPhServiceId(String phUnitId, String serviceId) {
		this.phUnitId = phUnitId;
		this.serviceId = serviceId;
	}

	@Column(name = "PH_UNIT_ID", nullable = false, length = 20)
	public String getPhUnitId() {
		return this.phUnitId;
	}

	public void setPhUnitId(String phUnitId) {
		this.phUnitId = phUnitId;
	}

	@Column(name = "SERVICE_ID", nullable = false, length = 20)
	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TestPhServiceId))
			return false;
		TestPhServiceId castOther = (TestPhServiceId) other;

		return ((this.getPhUnitId() == castOther.getPhUnitId()) || (this
				.getPhUnitId() != null && castOther.getPhUnitId() != null && this
				.getPhUnitId().equals(castOther.getPhUnitId())))
				&& ((this.getServiceId() == castOther.getServiceId()) || (this
						.getServiceId() != null
						&& castOther.getServiceId() != null && this
						.getServiceId().equals(castOther.getServiceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPhUnitId() == null ? 0 : this.getPhUnitId().hashCode());
		result = 37 * result
				+ (getServiceId() == null ? 0 : this.getServiceId().hashCode());
		return result;
	}

}
