package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Theme generated by hbm2java
 */
@Entity
@Table(name = "THEME")
public class Theme implements java.io.Serializable {

	private String themeId;
	private String name;
	private String description;
	private Set<SystemLogin> systemLogins = new HashSet<SystemLogin>(0);

	public Theme() {
	}

	public Theme(String themeId, String name, String description) {
		this.themeId = themeId;
		this.name = name;
		this.description = description;
	}

	public Theme(String themeId, String name, String description,
			Set<SystemLogin> systemLogins) {
		this.themeId = themeId;
		this.name = name;
		this.description = description;
		this.systemLogins = systemLogins;
	}

	@Id
	@Column(name = "THEME_ID", unique = true, nullable = false, length = 5)
	public String getThemeId() {
		return this.themeId;
	}

	public void setThemeId(String themeId) {
		this.themeId = themeId;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "theme")
	public Set<SystemLogin> getSystemLogins() {
		return this.systemLogins;
	}

	public void setSystemLogins(Set<SystemLogin> systemLogins) {
		this.systemLogins = systemLogins;
	}

}
