package com.kilbees.bussiness.model;
// default package
// Generated Sep 21, 2013 7:48:48 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UnitToken generated by hbm2java
 */
@Entity
@Table(name = "UNIT_TOKEN")
public class UnitToken implements java.io.Serializable {

	private UnitTokenId id;
	private BigDecimal cosmpType;

	public UnitToken() {
	}

	public UnitToken(UnitTokenId id, BigDecimal cosmpType) {
		this.id = id;
		this.cosmpType = cosmpType;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "unitNo", column = @Column(name = "UNIT_NO", nullable = false, length = 20)),
			@AttributeOverride(name = "tokenNo", column = @Column(name = "TOKEN_NO", nullable = false, precision = 38, scale = 0)) })
	public UnitTokenId getId() {
		return this.id;
	}

	public void setId(UnitTokenId id) {
		this.id = id;
	}

	@Column(name = "COSMP_TYPE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getCosmpType() {
		return this.cosmpType;
	}

	public void setCosmpType(BigDecimal cosmpType) {
		this.cosmpType = cosmpType;
	}

}
